import React, { useState, useEffect, useContext } from 'react';
import { Language } from '../types';
import { LanguageContext } from '../contexts/LanguageContext';

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.containers': 'Containers',
    'nav.gateIn': 'Gate In',
    'nav.gateOut': 'Gate Out',
    'nav.bookingReference': 'Booking Reference',
    'nav.releases': 'Release Orders',
    'nav.edi': 'EDI Management',
    'nav.yard': 'Yard Management',
    'nav.reports': 'Reports',
    'nav.configurations': 'Configurations',
    'nav.depotManagement': 'Depot Management',
    'nav.stackManagement': 'Stack Management',
    'nav.clientPools': 'Client Pools',
    'nav.clientMasterData': 'Client Master Data',
    'nav.userManagement': 'User Management',
    'nav.moduleAccess': 'Module Access',
    'nav.logout': 'Sign Out',

    // Dashboard
    'dashboard.title': 'Container Depot Management',
    'dashboard.welcome': 'Welcome back',
    'dashboard.stats.containers': 'Total Containers',
    'dashboard.stats.in': 'Containers In',
    'dashboard.stats.out': 'Containers Out',
    'dashboard.stats.pending': 'Pending Release Orders',
    'dashboard.stats.movements': 'Today\'s Movements',
    'dashboard.stats.revenue': 'Monthly Revenue',
    'dashboard.stats.occupancy': 'Occupancy Rate',
    'dashboard.stats.damaged': 'Damaged Containers',
    'dashboard.stats.maintenance': 'In Maintenance',
    'dashboard.stats.cleaning': 'In Cleaning',
    'dashboard.multiDepot.global': 'Global Performance',
    'dashboard.multiDepot.current': 'Current Depot',
    'dashboard.multiDepot.allDepots': 'All Depots',
    'dashboard.clientNotice': 'You are viewing data for your company only',

    // Containers
    'containers.title': 'Container Management',
    'containers.gate_in': 'Gate In',
    'containers.gate_out': 'Gate Out',
    'containers.search': 'Search containers...',
    'containers.searchYour': 'Search your containers...',
    'containers.status.inDepot': 'In Depot',
    'containers.status.outDepot': 'Out Depot',
    'containers.status.inService': 'In Service',
    'containers.status.maintenance': 'Maintenance',
    'containers.status.cleaning': 'Cleaning',
    'containers.type.dry': 'Dry Container',
    'containers.type.reefer': 'Reefer Container',
    'containers.type.tank': 'Tank Container',
    'containers.type.flatRack': 'Flat Rack',
    'containers.type.openTop': 'Open Top',
    'containers.size.20ft': '20 Feet',
    'containers.size.40ft': '40 Feet',
    'containers.viewDetails': 'View Details',
    'containers.editContainer': 'Edit Container',
    'containers.auditLog': 'Audit Log',
    'containers.damage.reports': 'Damage Reports',
    'containers.damage.none': 'No damage reports recorded',
    'containers.damage.add': 'Add Damage Report',
    'containers.damage.describe': 'Describe damage...',
    'containers.export.csv': 'Export CSV',
    'containers.export.excel': 'Export Excel',
    'containers.export.html': 'Export HTML',
    'containers.export.button': 'Export',
    'containers.list.noContainers': 'No containers found',
    'containers.list.noContainersClient': 'No containers found for your company. Contact the depot if you expect to see containers here.',
    'containers.table.gateIn': 'Gate In',
    'containers.table.gateOut': 'Gate Out',
    'containers.table.fullEmpty': 'Full / Empty',
    'containers.table.damagesReported': 'damage(s) reported',
    'containers.table.container': 'Container',
    'containers.filter.from': 'From',
    'containers.filter.to': 'To',
    'containers.filter.filterByClient': 'Filter by client...',
    'containers.filter.allStatus': 'All Status',
    'containers.stats.yourContainers': 'Your Containers',
    'containers.stats.withDamage': 'With Damage',
    'containers.details.title': 'Container Details',
    'containers.details.statusType': 'Status & Type Details',
    'containers.details.yourCompany': 'Your Company',
    'containers.details.days': 'days',
    'containers.edit.steps.location': 'Location Assignment',
    'containers.edit.steps.damage': 'Damage Assessment',
    'containers.edit.steps.review': 'Review & Confirm',
    'containers.edit.validationErrors': 'Validation Errors:',
    'containers.edit.validating': 'Validating...',
    'containers.edit.noPermission': 'You do not have permission to edit containers.',
    'containers.delete.title': 'Delete Container',
    'containers.delete.confirmMessage': 'This will mark the container as deleted.',
    'containers.delete.success': 'Container deleted successfully!',
    'containers.update.success': 'Container updated successfully!',
    'containers.delete.blocked': 'Cannot delete this container:',
    'containers.delete.actionRequired': 'Action Required:',

    // Gate Operations
    'gate.in.title': 'Gate In Management',
    'gate.in.new': 'New Gate In',
    'gate.in.pending': 'Pending Operations',
    'gate.in.completed': 'Completed Operations',
    'gate.in.stats.today': 'Today\'s Gate Ins',
    'gate.in.stats.pending': 'Pending Operations',
    'gate.in.stats.processed': 'Containers Processed',
    'gate.in.stats.damaged': 'Damaged Containers',
    'gate.in.form.containerInfo': 'Container Information',
    'gate.in.form.transportInfo': 'Transport Information',
    'gate.in.form.timeTracking': 'Time Tracking',
    'gate.in.form.containerNumber': 'Container Number',
    'gate.in.form.containerSize': 'Container Size',
    'gate.in.form.containerType': 'Container Type',
    'gate.in.form.quantity': 'Quantity',
    'gate.in.form.status': 'Container Status',
    'gate.in.form.damage': 'Damage Status',
    'gate.in.form.client': 'Client',
    'gate.in.form.booking': 'Booking Reference',
    'gate.in.form.driver': 'Driver Name',
    'gate.in.form.truck': 'Truck Number',
    'gate.in.form.transport': 'Transport Company',
    'gate.in.form.arrivalDate': 'Arrival Date',
    'gate.in.form.arrivalTime': 'Arrival Time',
    'gate.in.form.highCube': 'Is High Cube ?',
    'gate.in.form.equipmentRef': 'Equipment Reference',
    'gate.in.form.searchClient': 'Search client by name or code...',
    'gate.in.form.arrival': 'Truck Arrival Time',
    'gate.in.validation.required': 'This field is required',
    'gate.in.validation.containerFormat': 'Invalid container number format',
    'gate.in.validation.validFormat': 'Valid format',

    'gate.out.title': 'Gate Out Management',
    'gate.out.new': 'New Gate Out',
    'gate.out.pending': 'Pending Operations',
    'gate.out.stats.today': 'Today\'s Gate Outs',
    'gate.out.stats.pending': 'Pending Operations',
    'gate.out.stats.processed': 'Containers Processed',
    'gate.out.stats.issues': 'Issues Reported',
    'gate.out.form.booking': 'Booking Selection',
    'gate.out.form.transport': 'Transport Information',
    'gate.out.form.containers': 'Container Numbers',
    'gate.out.form.selectBooking': 'Select Booking',
    'gate.out.form.driver': 'Driver Name',
    'gate.out.form.vehicle': 'Vehicle Number',
    'gate.out.form.company': 'Transport Company',
    'gate.out.form.vehicleNumberError': 'Truck {truck} has a pending operation in progress. Please complete or cancel the existing operation before proceeding.',
    'gate.out.completion.submit': 'Complete Gate Out',
    'gate.out.truckRules.title': 'Truck Capacity Rules',
    'gate.out.truckRules.40ft': 'Maximum 1 container of 40ft per truck',
    'gate.out.truckRules.20ft': 'Maximum 2 containers of 20ft per truck',
    'gate.out.truckRules.mix': 'Cannot mix 20ft and 40ft containers in same truck',
    'gate.out.truckRules.disabled40ft': 'Disabled (40ft truck full)',
    'gate.out.error.containerNotFound': 'Container not found in yard',
    'gate.out.error.invalidStatus': 'Invalid status: {status}',
    'gate.out.success.validated': 'Container Validated',
    'gate.out.completion.containers': 'Container Numbers',
    'gate.out.completion.confirm': 'Confirm Container Number',
    'gate.out.completion.gateOutTime': 'Gate Out Date & Time',
    'gate.in.subtitle': 'Container entry management',
    'gate.in.search': 'Search operations...',
    'gate.in.stats.alimentaire': 'Alimentaire Containers',
    'gate.in.success': 'Gate In operation completed successfully',
    'gate.in.summary': 'Operation Summary',
    'gate.in.pendingNotice.title': 'Pending Operation',
    'gate.in.pendingNotice.desc': 'This Gate In operation will be created with Pending status. Stack assignment and damage assessment will be done later.',
    'gate.out.subtitle': 'Container exit management',
    'gate.out.summary': 'Operation Summary',
    'gate.out.form.searchBooking': 'Search and select a booking...',
    'gate.out.form.selectedBooking': 'Selected Booking',
    'gate.out.form.selectBookingMessage': 'Please select a booking to continue.',
    'common.fixErrors': 'Please fix the following errors:',
    'common.pleaseReview': 'Please review:',
    'common.submissionFailed': 'Submission Failed',

    // Release Orders
    'releases.title': 'Release Orders',
    'releases.booking.title': 'Booking Management',
    'releases.create': 'Create Release Order',
    'releases.createBooking': 'Create Booking',
    'releases.pending': 'Pending Validation',
    'releases.validated': 'Validated',
    'releases.executed': 'Executed',
    'releases.completed': 'Completed',
    'releases.cancelled': 'Cancelled',
    'releases.inProcess': 'In Process',
    'releases.stats.total': 'Total Bookings',
    'releases.stats.pending': 'Pending',
    'releases.stats.validated': 'Validated',
    'releases.stats.completed': 'Completed',
    'releases.form.bookingInfo': 'Booking Information',
    'releases.form.clientInfo': 'Client Information',
    'releases.form.quantities': 'Container Quantities',
    'releases.form.bookingNumber': 'Booking Reference Number',
    'releases.form.bookingType': 'Booking Type',
    'releases.form.client': 'Select Client',
    'releases.form.threshold': 'Maximum Quantity Threshold',
    'releases.form.containers20': '20" Containers',
    'releases.form.containers40': '40" Containers',
    'releases.form.notes': 'Notes',
    'releases.breakdown.required': 'Detailed breakdown required',
    'releases.breakdown.summary': 'Container Summary',
    'releases.subtitle': 'Release orders & container bookings',
    'releases.search': 'Search bookings...',
    'releases.subtitle.edit': 'Update booking reference',
    'releases.subtitle.create': 'Generate new booking reference',
    'releases.form.bookingDesc': 'Define the booking type and reference number',
    'releases.form.refImmutable': 'Reference number cannot be changed',
    'releases.form.refHelp': 'This will be used as the booking ID throughout the application',
    'releases.form.clientDesc': 'Select the client for this booking',
    'releases.form.qtyControl': 'Quantity Control',
    'releases.form.qtyControlDesc': 'Set limits for container allocation',
    'releases.form.thresholdHelp': 'Maximum containers allowed before requiring detailed breakdown per size',
    'releases.form.quantitiesTitle': 'Container Quantities by Size',
    'releases.breakdown.help': 'Total exceeds threshold. Detailed breakdown will be required for processing.',
    'gate.out.stats.remaining': 'Containers Remaining',
    'common.createdBy': 'Created by',
    'common.createdDate': 'Created Date',
    'common.updatedDate': 'Updated Date',
    'common.standard': 'Standard',
    'common.highCapacity': 'High Capacity',
    'common.summary': 'Summary',

    // Yard Management
    'yard.title': 'Yard Management',
    'yard.loading': 'Loading Yard Management...',
    'yard.noYardSelected': 'No yard selected',
    'yard.selectYardMessage': 'Please select a yard to continue',
    'yard.search': 'Container Search',
    'yard.searchContainer': 'Search & Locate',
    'yard.selectedContainer': 'Selected Container',
    'yard.resetView': 'Reset to Full Yard View',
    'yard.resetViewShort': 'Reset View',
    'yard.occupancy': 'Occupancy',
    'yard.capacity': 'Capacity',
    'yard.utilization': 'Utilization',
    'yard.sections': 'Sections',
    'yard.stacks': 'Total Stacks',
    'yard.stackCapacity': 'Total Stack Capacity',
    'yard.containersVisible': 'containers visible',
    'yard.selected': 'selected',
    'yard.zoomIn': 'Zoom In',
    'yard.zoomOut': 'Zoom Out',
    'yard.showLegend': 'Show Legend',
    'yard.hideLegend': 'Hide Legend',
    'yard.legend.title': 'Legend',
    'yard.legend.tips': 'Tips:',
    'yard.legend.tip1': 'Click containers to select',
    'yard.legend.tip2': 'Right-click + drag to pan',
    'yard.legend.tip3': 'Scroll to zoom in/out',
    'yard.legend.availableSlot': 'Available Slot',
    'yard.legend.availableSlotDesc': 'Empty container position',
    'yard.legend.containerInDepot': 'Container In Depot',
    'yard.legend.containerInDepotDesc': 'Container stored in yard',
    'yard.legend.underMaintenance': 'Under Maintenance',
    'yard.legend.underMaintenanceDesc': 'Container being repaired',
    'yard.legend.beingCleaned': 'Being Cleaned',
    'yard.legend.beingCleanedDesc': 'Container in cleaning process',
    'yard.legend.damagedContainer': 'Damaged Container',
    'yard.legend.damagedContainerDesc': 'Container with damage reports',
    'yard.legend.selectedContainer': 'Selected Container',
    'yard.legend.selectedContainerDesc': 'Currently selected container',
    'yard.stats.title': 'Yard Statistics',
    'yard.stats.activeContainers': 'Active Containers',
    'yard.stats.maintenance': 'Under Maintenance',
    'yard.stats.cleaning': 'Being Cleaned',
    'yard.stats.damaged': 'Damaged',
    'yard.stats.totalStacks': 'Total Stacks',
    'yard.info.title': 'Yard Information',
    'yard.info.layout': 'Layout:',
    'yard.info.sections': 'Sections:',
    'yard.info.totalCapacity': 'Total Capacity:',
    'yard.info.currentOccupancy': 'Current Occupancy:',

    // Depot Management
    'depot.title': 'Depot Management',
    'depot.create': 'Create Depot',
    'depot.edit': 'Edit Depot',
    'depot.view': 'View Details',
    'depot.assign': 'Assign Users',
    'depot.delete': 'Delete Depot',
    'depot.stats.total': 'Total Depots',
    'depot.stats.active': 'Active Depots',
    'depot.stats.capacity': 'Total Capacity',
    'depot.stats.occupancy': 'Total Occupancy',
    'depot.form.basicInfo': 'Basic Information',
    'depot.form.contactInfo': 'Contact Information',
    'depot.form.address': 'Address Information',
    'depot.form.name': 'Depot Name',
    'depot.form.code': 'Depot Code',
    'depot.form.description': 'Description',
    'depot.form.location': 'Location',
    'depot.form.capacity': 'Total Capacity',
    'depot.form.layout': 'Layout Type',
    'depot.form.manager': 'Manager Name',
    'depot.form.phone': 'Phone',
    'depot.form.email': 'Email',
    'depot.form.street': 'Street Address',
    'depot.form.city': 'City',
    'depot.form.state': 'State/Region',
    'depot.form.zipCode': 'ZIP Code',
    'depot.form.country': 'Country',
    'depot.form.timezone': 'Timezone',
    'depot.form.status': 'Status',
    'depot.layout.yirima': 'Yirima Grid',
    'depot.layout.tantarelli': 'Tantarelli Layout',

    // Stack Management
    'stack.title': 'Stack Management',
    'stack.subtitle': 'Configure container size assignments for all stacks',
    'stack.configuration': 'Stack Configuration',
    'stack.configuration.desc': 'Configure container size assignments for each stack (paired stacks will be updated together)',
    'stack.create': 'Create Stack',
    'stack.edit': 'Edit Stack',
    'stack.delete': 'Delete Stack',
    'stack.refresh': 'Refresh',
    'stack.refreshing': 'Refreshing...',
    'stack.rules': 'Configuration Rules',
    'stack.pairing': 'Valid Stack Pairs for 40ft Containers',
    'stack.search': 'Search stacks or sections...',
    'stack.size20': '20ft',
    'stack.size40': '40ft',
    'stack.special': 'Special',
    'stack.regular': 'Regular',
    'stack.assigned': 'Assigned Client',
    'stack.unassigned': 'Unassigned',
    'stack.exclusive': 'Exclusive',
    'stack.shared': 'Shared',
    'stack.saveChanges': 'Save Changes',
    'stack.resetChanges': 'Reset',
    'stack.rules.special': 'Special Stacks (01, 31, 101, 103): Can only be set to 20ft containers.',
    'stack.rules.regular': 'Regular Stacks: Can be set to either 20ft or 40ft containers.',
    'stack.rules.pairing': '40ft Assignment: Only available for regular stacks that have an adjacent regular stack to form valid pairs.',
    'stack.rules.updates': 'Paired Updates: When changing a regular stack to 40ft, its adjacent pair will automatically be updated to match.',
    'stack.refreshed': 'Stack configuration refreshed successfully!',
    'stack.delete.title': 'Soft Delete Stack',
    'stack.delete.confirm': 'Are you sure you want to soft delete Stack S{number}? This will deactivate the stack and all its locations, but preserve all data for potential recovery. You can reactivate it later if needed.',
    'stack.delete.success': 'Stack S{number} soft deleted successfully! You can reactivate it later if needed.',
    'stack.delete.error': 'Failed to soft delete stack',
    'stack.update.success': 'Stack updated successfully!',
    'stack.create.success': 'Stack created successfully!',
    'stack.sizeUpdate.success': 'Stack updated to {size} successfully!',
    'stack.sizeUpdate.successMulti': 'Successfully updated {count} stacks to {size}!',
    'stack.sizeUpdate.errorOccupied': 'Cannot change stack size: Virtual stack locations are occupied. Please relocate all containers from the paired stacks first.',
    'stack.assign.success': 'Stack assigned to client {client} successfully!',
    'stack.unassigned.success': 'Stack unassigned from client pool successfully!',
    'stack.noStacks': 'No stacks found. Create your first stack to get started.',
    'stack.stats.total': 'Total Stacks',
    'stack.stats.40ft': 'Total 40ft Stacks',
    'stack.stats.20ft': 'Total 20ft Stacks',
    'stack.stats.special': 'Special Stacks',
    'stack.stats.regular': 'Regular Stacks',
    'stack.stats.clientAssigned': 'Client Assigned',
    'stack.stats.all': 'All stacks',
    'stack.stats.logicalPairs': 'Logical pairs',
    'stack.stats.single': 'Single stacks',
    'stack.stats.buffer': 'Buffer zones',
    'stack.stats.standardOps': 'Standard ops',
    'stack.stats.unassignedCount': '{count} unassigned',
    'stack.table.stack': 'Stack',
    'stack.table.section': 'Section',
    'stack.table.containerSize': 'Container Size',
    'stack.table.assignedClient': 'Assigned Client',
    'stack.table.capacity': 'Capacity',
    'stack.table.actions': 'Actions',
    'stack.table.manage': 'Manage',
    'stack.table.pair': 'Pair',
    'stack.table.noPair': 'No pair',
    'stack.table.specialNo40': 'Special stacks cannot be configured for 40ft',
    'stack.table.updatePair': 'Will also update Stack {number}',
    'stack.advancedFilter': 'Advanced Filter',
    'stack.allStacks': 'All Stacks',
    'stack.allSections': 'All Sections',
    'stack.help.title': 'Stack Configuration Help',
    'stack.help.desc': 'View rules and guidelines for managing yard stacks.',
    'stack.loadingConfig': 'Please wait while we load the yard configuration.',
    'stack.form.information': 'Stack Information',
    'stack.form.number': 'Stack Number',
    'stack.form.section': 'Section',
    'stack.form.sizeConfig': 'Container Size Configuration',
    'stack.form.typeConfig': 'Stack Type Configuration',
    'stack.form.capacityConfig': 'Capacity Configuration',
    'stack.form.dimensions': 'Stack Dimensions',
    'stack.form.dimensionsDesc': 'Configure the physical layout of your stack',
    'stack.form.rows': 'Rows (Depth)',
    'stack.form.tiers': 'Max Tiers (Height)',
    'stack.form.customTiers': 'Custom Tier Configuration',
    'stack.form.preview': 'Stack Preview',
    'stack.form.useSuggested': 'Use {number}',
    'stack.form.suggested': 'Suggested: {number}',
    'stack.form.differentFromSuggested': 'Different from suggested',
    'stack.form.usingSuggested': 'Using suggested',
    'stack.form.selectSection': 'Select section',
    'stack.form.noSections': 'No sections available',
    'stack.form.sectionImmutable': 'Section cannot be changed when editing an existing stack',
    'stack.form.20ftDesc': 'Standard Size',
    'stack.form.40ftDesc': 'High Capacity',
    'stack.form.specialWarning': 'Special stacks are limited to 20ft containers only',
    'stack.form.regularDesc': 'Standard Operations',
    'stack.form.specialDesc': 'Limited Operations',
    'stack.form.rowsDesc': 'Container rows from front to back',
    'stack.form.tiersDesc': 'Maximum containers stacked vertically',
    'stack.form.customTiersDesc': 'Configure different maximum tier heights for each row based on ground conditions or equipment limitations',
    'stack.form.previewLayout': 'Stack Layout Preview',
    'stack.form.totalCapacity': 'Total Stack Capacity',
    'stack.form.capacityDesc': 'Maximum container positions available',
    'stack.form.positions': 'Container positions',
    'stack.form.uniformLayout': 'Uniform layout',
    'stack.form.customLayout': 'Custom layout',
    'stack.form.calculation': 'Calculation',
    'stack.form.specialNotice': 'This stack will be limited to 20ft containers only and cannot accommodate 40ft containers.',
    'stack.form.40ftNotice': 'This stack will be configured for high-capacity 40ft containers and may require pairing with adjacent stacks.',
    'stack.validation.numberRequired': 'Stack number must be greater than 0',
    'stack.validation.sectionRequired': 'Section is required',
    'stack.validation.rowsRange': 'Rows must be between 1 and 10',
    'stack.validation.tiersRange': 'Max tiers must be between 1 and 8',
    'stack.validation.specialNo40': 'Special stacks can only accommodate 20ft containers',
    'stack.validation.rowChangeError': 'Unable to validate row change. Please try again.',




    // Client Pools
    'clientPools.title': 'Client Pool Management',
    'clientPools.create': 'Create Client Pool',
    'clientPools.edit': 'Edit Client Pool',
    'clientPools.stats.total': 'Total Pools',
    'clientPools.stats.active': 'Active Clients',
    'clientPools.stats.stacks': 'Assigned Stacks',
    'clientPools.stats.utilization': 'Avg Utilization',
    'clientPools.form.clientInfo': 'Client Information',
    'clientPools.form.stackAssignment': 'Stack Assignment',
    'clientPools.form.additionalInfo': 'Additional Information',
    'clientPools.form.selectClient': 'Select Client',
    'clientPools.form.contractStart': 'Contract Start Date',
    'clientPools.form.contractEnd': 'Contract End Date',
    'clientPools.form.notes': 'Notes & Special Instructions',
    'clientPools.form.capacity': 'Capacity',
    'clientPools.form.selected': 'Selected',
    'clientPools.form.stacks': 'stacks',
    'clientPools.form.containers': 'containers',
    'clientPools.priority.high': 'High',
    'clientPools.priority.medium': 'Medium',
    'clientPools.subtitle': 'Manage customer-specific stack assignments and capacity allocation',
    'clientPools.search': 'Search client pools...',
    'clientPools.overview': 'Client Pool Overview',
    'clientPools.table.stacks': 'stacks',
    'clientPools.table.viewStacks': 'View stack details →',
    'clientPools.noPools': 'No client pools found',
    'clientPools.noPoolsEmpty': 'No client pools have been created yet.',
    'clientPools.delete.title': 'Delete Client Pool',
    'clientPools.delete.confirm': 'Are you sure you want to delete the pool for {client}? This action cannot be undone.',
    'clientPools.utilization.title': 'Pool Utilization Overview',
    'clientPools.form.subtitle.edit': 'Update client pool configuration',
    'clientPools.form.subtitle.create': 'Assign dedicated stacks to a client',
    'clientPools.form.selectClientPlaceholder': 'Select a client...',
    'clientPools.form.selectStacks': 'Select Stacks',
    'clientPools.form.modifySelection': 'Modify Selection',
    'clientPools.form.noStacks': 'No Stacks Selected',
    'clientPools.form.noStacksHelp': 'Click the button above to select stacks for this client pool',
    'clientPools.form.noAvailableStacks': 'No Available Stacks',
    'clientPools.form.noAvailableStacksHelp': 'All stacks are currently assigned to other clients',
    'clientPools.form.progress.client': 'Client Selected',
    'clientPools.form.progress.stacks': 'Stacks Assigned',
    'clientPools.form.progress.contract': 'Contract Date Set',
    'clientPools.stackSelection.title': 'Select Stacks for Client Pool',
    'clientPools.stackSelection.subtitle': 'Choose stacks to assign to {client} (Physical stacks only - virtual stacks assigned automatically)',

    // Client Master Data
    'clients.title': 'Client Master Data',
    'clients.add': 'Add Client',
    'clients.edit': 'Edit Client',
    'clients.view': 'View Details',
    'clients.delete': 'Delete Client',
    'clients.stats.total': 'Total Customers',
    'clients.stats.active': 'Active Customers',
    'clients.stats.creditLimit': 'Total Credit Limit',
    'clients.stats.avgPayment': 'Avg Payment Terms',
    'clients.form.basicInfo': 'Basic Information',
    'clients.form.address': 'Company Address',
    'clients.form.contact': 'Contact Person',
    'clients.form.billing': 'Billing Address',
    'clients.form.financial': 'Financial Configuration',
    'clients.form.name': 'Company Name',
    'clients.search': 'Search clients...',
    'clients.noClients': 'No clients found',
    'clients.noClientsEmpty': 'Get started by adding your first client.',
    'clients.delete.title': 'Delete Client',
    'clients.delete.confirm': 'Are you sure you want to delete {client}? This action cannot be undone.',
    'clients.success.update': 'Client updated successfully!',
    'clients.success.create': 'Client created successfully!',
    'clients.success.delete': 'Client deleted successfully!',
    'clients.error.save': 'Error saving client:',
    'clients.table.contact': 'Contact Information',
    'clients.form.subtitle.edit': 'Modification of client {client}',
    'clients.form.subtitle.create': 'Creation of a new client',
    'clients.form.step.basic': 'Basic Information',
    'clients.form.step.address': 'Address & Contact',
    'clients.form.step.config': 'Configuration',
    'clients.form.companyName': 'Company Name',
    'clients.form.mainEmail': 'Main Email',
    'clients.form.mainPhone': 'Main Phone',
    'clients.form.taxId': 'Tax Identification Number',
    'clients.form.addressTitle': 'Company Address',
    'clients.form.addressDesc': 'Location and company details',
    'clients.form.street': 'Full Address',
    'clients.form.city': 'City',
    'clients.form.district': 'Commune/District',
    'clients.form.zipCode': 'Zip Code',
    'clients.form.country': 'Country',
    'clients.form.contactTitle': 'Contact Person',
    'clients.form.contactDesc': 'Main person responsible for communications',
    'clients.form.contactName': 'Full Name',
    'clients.form.contactPosition': 'Position/Job Title',
    'clients.form.contactEmail': 'Contact Email',
    'clients.form.contactPhone': 'Contact Phone',
    'clients.form.billingTitle': 'Billing Address',
    'clients.form.billingDesc': 'Address for sending invoices',
    'clients.form.sameAddress': 'Same as company address',
    'clients.form.financialTitle': 'Financial Configuration',
    'clients.form.financialDesc': 'Billing settings and payment terms',
    'clients.form.creditLimit': 'Credit Limit',
    'clients.form.paymentTerms': 'Payment Terms (days)',
    'clients.form.freeDays': 'Free Storage Days',
    'clients.form.dailyRate': 'Daily Rate',
    'clients.form.currency': 'Currency',
    'clients.form.previewTitle': 'Billing Preview',
    'clients.form.previewDesc': 'Simulation of storage costs',
    'clients.form.freeDaysLabel': 'Free Days',
    'clients.form.rateLabel': 'Rate/Day',
    'clients.form.termsLabel': 'Payment Days',
    'clients.form.calculationExample': 'Calculation example:',
    'clients.form.exampleTenDays': 'Container placed for 10 days',
    'clients.form.exampleFreeDays': 'Free days:',
    'clients.form.exampleBillable': 'Billable days:',
    'clients.form.exampleTotal': 'Total amount:',
    'clients.form.notesTitle': 'Notes and Special Instructions',
    'clients.form.notesDesc': 'Additional information and specific instructions',
    'clients.form.systemTitle': 'System Configuration',
    'clients.form.systemDesc': 'System settings and integrations',
    'clients.form.activeLabel': 'Active Client',
    'clients.form.activeDesc': 'The client can perform operations',
    'clients.form.autoEdiLabel': 'Automatic EDI Transmission',
    'clients.form.autoEdiDesc': 'Automatic sending of CODECO messages',
    'clients.form.ediActive': 'EDI Transmission activated:',
    'clients.form.notes': 'Notes and Special Instructions',
    'clients.form.active': 'Active Client',

    // User Management
    'users.title': 'User Management',
    'users.add': 'Add User',
    'users.edit': 'Edit User',
    'users.view': 'View Details',
    'users.delete': 'Delete User',
    'users.stats.total': 'Total Users',
    'users.stats.active': 'Active Users',
    'users.stats.admins': 'Administrators',
    'users.stats.online': 'Online Today',
    'users.form.basicInfo': 'Basic Information',
    'users.form.role': 'User Role',
    'users.form.yardAssignments': 'Yard Assignments',
    'users.form.name': 'Full Name',
    'users.form.email': 'Email Address',
    'users.form.phone': 'Phone Number',
    'users.form.department': 'Department',
    'users.form.company': 'Company',
    'users.form.password': 'Password',
    'users.form.active': 'Active User',
    'users.role.admin': 'Administrator',
    'users.subtitle.managing': 'Managing users for:',
    'users.search': 'Search users...',
    'users.noUsers': 'No users found',
    'users.noUsersEmpty': 'Get started by adding your first user',
    'users.delete.title': 'Delete User',
    'users.delete.confirm': 'Are you sure you want to delete {user}? This action will safely remove the user from the system while preserving data integrity.',
    'users.success.update': 'User updated successfully',
    'users.success.create': 'User created successfully',
    'users.success.delete': 'User deleted successfully',
    'users.error.save': 'Failed to save user',
    'users.error.delete': 'Failed to delete user',
    'users.table.user': 'User',
    'users.table.role': 'Role',
    'users.table.department': 'Department',
    'users.table.lastLogin': 'Last Login',
    'users.form.subtitle.edit': 'Update user information and permissions',
    'users.form.subtitle.create': 'Add a new user to the system',
    'users.form.status': 'User Status',
    'users.form.profileInfo': 'Profile Information',
    'users.form.permissionsOverview': 'Permissions Overview',
    'users.activity.recent': 'Recent Activity',
    'users.activity.history': 'Login History',
    'users.validation.nameRequired': 'Full name is required',
    'users.validation.nameMin': 'Name must be at least 2 characters',
    'users.validation.nameMax': 'Name must be less than 100 characters',
    'users.validation.emailRequired': 'Email address is required',
    'users.validation.emailInvalid': 'Please enter a valid email address',
    'users.validation.phoneInvalid': 'Please enter a valid phone number',
    'users.validation.passwordRequired': 'Password is required for new users',
    'users.validation.passwordMin': 'Password must be at least 6 characters',
    'users.validation.passwordMax': 'Password must be less than 128 characters',
    'users.role.description.admin': 'Full system access across all modules',
    'users.role.description.supervisor': 'Operations oversight and management',
    'users.role.description.operator': 'Daily operations and container handling',
    'users.role.description.client': 'View containers and create release orders',
    'common.time.never': 'Never',
    'common.time.justNow': 'Just now',
    'common.time.hoursAgo': 'h ago',
    'common.time.daysAgo': 'd ago',
    'users.role.supervisor': 'Supervisor',
    'users.role.operator': 'Operator',
    'users.role.client': 'Client',
    'users.role.adminDesc': 'Full system access across all modules',
    'users.role.supervisorDesc': 'Operations oversight and management',
    'users.role.operatorDesc': 'Daily operations and container handling',
    'users.role.clientDesc': 'View containers and create release orders',

    // Module Access
    'moduleAccess.title': 'Module Access Management',
    'moduleAccess.bulkActions': 'Bulk Actions',
    'moduleAccess.applyRoleBased': 'Apply Role-Based Access',
    'moduleAccess.enableAll': 'Enable All',
    'moduleAccess.disableAll': 'Disable All',
    'moduleAccess.selectAll': 'Select All',
    'moduleAccess.deselectAll': 'Deselect All',
    'moduleAccess.stats.totalUsers': 'Total Users',
    'moduleAccess.stats.modules': 'Available Modules',
    'moduleAccess.stats.admins': 'Admin Users',
    'moduleAccess.stats.selected': 'Selected Users',
    'moduleAccess.category.core': 'Core',
    'moduleAccess.category.operations': 'Operations',
    'moduleAccess.category.management': 'Management',
    'moduleAccess.category.admin': 'Admin',
    'moduleAccess.roleRestricted': 'Role Restricted',
    'moduleAccess.protected': 'Protected',
    'moduleAccess.system': 'System',

    // Reports & Analytics
    'reports.title': 'Reports & Analytics',
    'reports.billing': 'Billing & Free Days',
    'reports.analytics': 'Analytics',
    'reports.operations': 'Operations',
    'reports.export': 'Export Report',
    'reports.dateRange': 'Date Range',
    'reports.startDate': 'Start date',
    'reports.endDate': 'End date',
    'reports.currentDepot': 'Current Depot',
    'reports.allDepots': 'All Depots',
    'reports.globalView': 'Global View',
    'reports.billing.title': 'Container Billing Details',
    'reports.billing.freeDays': 'Free days calculation and billing information',
    'reports.billing.totalRevenue': 'Total Revenue',
    'edi.title': 'EDI Management',
    'edi.subtitle': 'Manage EDI transmissions, server configurations, and client settings',
    'edi.configuration': 'Configuration',
    'edi.tabs.overview': 'Overview',
    'edi.tabs.servers': 'FTP/SFTP Servers',
    'edi.tabs.clients': 'Client EDI Settings',
    'edi.tabs.validator': 'EDI Validator',
    'edi.tabs.history': 'Transmission History',
    'edi.stats.total': 'Total Operations',
    'edi.stats.success': 'EDI Success Rate',
    'edi.stats.clients': 'Clients with EDI',
    'edi.stats.servers': 'Servers Configured',
    'edi.recentOperations': 'Recent EDI Operations',
    'edi.servers.title': 'FTP/SFTP Server Configuration',
    'edi.servers.configure': 'Configure Servers',
    'edi.servers.emptyAction': 'Configure your first server',
    'edi.clients.title': 'Client EDI Settings',
    'edi.clients.empty': 'No clients configured for EDI',
    'edi.clients.emptyAction': 'Configure your first client',
    'edi.history.title': 'Transmission History',
    'edi.history.empty': 'No transmission logs found',
    'edi.history.table.container': 'Container',
    'edi.history.table.operation': 'Operation',
    'edi.history.table.status': 'Status',
    'edi.history.table.client': 'Client',
    'edi.history.table.date': 'Transmission Date',
    'edi.error.load': 'Failed to load EDI data',
    'edi.success.refresh': 'Data refreshed successfully',
    'edi.success.retry': 'Transmission retry initiated',
    'edi.error.retry': 'Retry failed',
    'edi.success.clientDelete': 'Client EDI configuration removed',
    'edi.error.clientDelete': 'Failed to remove client EDI configuration',
    'edi.success.clientSave': 'Client EDI configuration saved',
    'edi.delete.confirm': 'Are you sure you want to remove EDI configuration for this client?',
    'edi.configModal.title': 'EDI Configuration',
    'edi.configModal.listTitle': 'Configurations',
    'edi.configModal.form.name': 'Configuration Name',
    'edi.configModal.form.type': 'Server Type',
    'edi.configModal.form.host': 'Host',
    'edi.configModal.form.port': 'Port',
    'edi.configModal.form.username': 'Username',
    'edi.configModal.form.password': 'Password',
    'edi.configModal.form.remotePath': 'Remote Path',
    'edi.configModal.form.partnerCode': 'Partner Code',
    'edi.configModal.form.senderCode': 'Sender Code',
    'edi.configModal.form.timeout': 'Timeout (ms)',
    'edi.configModal.form.retry': 'Retry Attempts',
    'edi.configModal.form.filePattern': 'File Name Pattern',
    'edi.configModal.form.assignedClients': 'Assigned Clients',
    'edi.configModal.form.noClients': 'No clients assigned',
    'edi.configModal.form.searchPlaceholder': 'Search or add client...',
    'edi.configModal.form.addCustom': 'Add "{client}"',
    'edi.configModal.emptyTitle': 'No Configuration Selected',
    'edi.configModal.emptyDesc': 'Select a configuration from the list to view details, or create a new one.',
    'edi.configModal.form.testMode': 'Test Mode',
    'edi.configModal.form.testModeDesc': 'In test mode, transmissions are simulated and no real files are uploaded.',
    'edi.configModal.form.isDefault': 'Set as Default',
    'edi.configModal.form.testConnection': 'Test Connection',
    'edi.configModal.form.passwordPlaceholder': 'Protected',
    'edi.configModal.form.filePatternHint': 'Tokens: {timestamp}, {container}, {operation}, {client}',
    'edi.configModal.defaultLabel': 'Default',
    'edi.clientModal.editTitle': 'Edit Client EDI Configuration',
    'edi.clientModal.createTitle': 'Add Client EDI Configuration',
    'edi.clientModal.form.enableEdi': 'Enable EDI for this client',
    'edi.clientModal.form.enableIn': 'Enable Gate In EDI',
    'edi.clientModal.form.enableOut': 'Enable Gate Out EDI',
    'edi.checkAcknowledgments': 'Check Acknowledgments',
    'edi.processFile': 'Process EDI from File',
    'edi.fileType': 'File Type',
    'edi.operation': 'Operation',
    'edi.selectFile': 'Select File',
    'edi.processSend': 'Process & Send',
    'edi.transmissionHistory': 'Transmission History',
    'edi.stats.sent': 'Total Sent',
    'edi.stats.pending': 'Pending',
    'edi.stats.failed': 'Failed',
    'edi.stats.acknowledged': 'Acknowledged',
    'edi.status.pending': 'Pending',
    'edi.status.sent': 'Sent',
    'edi.status.failed': 'Failed',
    'edi.status.acknowledged': 'Acknowledged',
    'edi.retry': 'Retry',
    'edi.view': 'View',

    // Common
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.delete': 'Delete',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.loading': 'Loading...',
    'common.processing': 'Processing...',
    'common.saving': 'Saving...',
    'common.updating': 'Updating...',
    'common.creating': 'Creating...',
    'common.deleting': 'Deleting...',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.info': 'Information',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.all': 'All',
    'common.none': 'None',
    'common.total': 'Total',
    'common.available': 'Available',
    'common.capacity': 'Capacity',
    'common.utilization': 'Utilization',
    'common.location': 'Location',
    'common.client': 'Client',
    'common.container': 'Container',
    'common.containers': 'Containers',
    'common.type': 'Type',
    'common.size': 'Size',
    'common.quantity': 'Quantity',
    'common.notes': 'Notes',
    'common.description': 'Description',
    'common.name': 'Name',
    'common.code': 'Code',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.city': 'City',
    'common.country': 'Country',
    'common.department': 'Department',
    'common.company': 'Company',
    'common.role': 'Role',
    'common.permission': 'Permission',
    'common.access': 'Access',
    'common.denied': 'Access Denied',
    'common.restricted': 'Access Restricted',
    'common.unauthorized': 'You don\'t have permission to access this module',
    'common.contactAdmin': 'Contact your administrator to request access',
    'common.noData': 'No data found',
    'common.noResults': 'No results found',
    'common.tryAdjusting': 'Try adjusting your search criteria',
    'common.selectDate': 'Select date',
    'common.selectTime': 'Select time',
    'common.currentTime': 'Current time',
    'common.today': 'Today',
    'common.yesterday': 'Yesterday',
    'common.tomorrow': 'Tomorrow',
    'common.thisWeek': 'This week',
    'common.thisMonth': 'This month',
    'common.lastMonth': 'Last month',
    'common.thisYear': 'This year',
    'common.damaged': 'Damaged',
    'common.undamaged': 'Good condition',
    'common.priority': 'Priority',
    'common.urgent': 'Urgent',
    'common.normal': 'Normal',
    'common.low': 'Low',
    'common.appSubtitle': 'Depot Management System (DMS)',
    'common.loggedInAs': 'Logged in as:',
    'common.install': 'Install',
    'common.newNotifications': 'New',
    'common.quickActions': 'Quick Actions',
    'common.appFooter': 'Container Depot Management v1.0',
    'common.copyright': '© 2025 DepotManager',
    'dashboard.stats.vsLastMonth': 'vs last month',
  },
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.containers': 'Conteneurs',
    'nav.gateIn': 'Entrée Portail',
    'nav.gateOut': 'Sortie Portail',
    'nav.bookingReference': 'Référence de Réservation',
    'nav.releases': 'Ordres de sortie',
    'nav.edi': 'Gestion EDI',
    'nav.yard': 'Gestion de Cour',
    'nav.reports': 'Rapports',
    'nav.configurations': 'Configurations',
    'nav.depotManagement': 'Gestion des Dépôts',
    'nav.stackManagement': 'Gestion des Piles',
    'nav.clientPools': 'Pools Clients',
    'nav.clientMasterData': 'Données Maîtres Clients',
    'nav.userManagement': 'Gestion des Utilisateurs',
    'nav.moduleAccess': 'Accès aux Modules',
    'nav.logout': 'Se déconnecter',

    // Dashboard
    'dashboard.title': 'Gestion de Dépôt de Conteneurs',
    'dashboard.welcome': 'Bon retour',
    'dashboard.stats.containers': 'Total Conteneurs',
    'dashboard.stats.in': 'Conteneurs Entrés',
    'dashboard.stats.out': 'Conteneurs Sortis',
    'dashboard.stats.pending': 'Ordres en Attente',
    'dashboard.stats.movements': 'Mouvements du Jour',
    'dashboard.stats.revenue': 'Revenus Mensuels',
    'dashboard.stats.occupancy': 'Taux d\'Occupation',
    'dashboard.stats.damaged': 'Conteneurs Endommagés',
    'dashboard.stats.maintenance': 'En Maintenance',
    'dashboard.stats.cleaning': 'En Nettoyage',
    'dashboard.multiDepot.global': 'Performance Globale',
    'dashboard.multiDepot.current': 'Dépôt Actuel',
    'dashboard.multiDepot.allDepots': 'Tous les Dépôts',
    'dashboard.clientNotice': 'Vous consultez les données de votre entreprise uniquement',

    // Containers
    'containers.title': 'Gestion des Conteneurs',
    'containers.gate_in': 'Entrée',
    'containers.gate_out': 'Sortie',
    'containers.search': 'Rechercher des conteneurs...',
    'containers.searchYour': 'Rechercher vos conteneurs...',
    'containers.status.inDepot': 'Dans le Dépôt',
    'containers.status.outDepot': 'Hors Dépôt',
    'containers.status.inService': 'En Service',
    'containers.status.maintenance': 'Maintenance',
    'containers.status.cleaning': 'Nettoyage',
    'containers.type.dry': 'Conteneur Sec',
    'containers.type.reefer': 'Conteneur Frigorifique',
    'containers.type.tank': 'Conteneur Citerne',
    'containers.type.flatRack': 'Plate-forme',
    'containers.type.openTop': 'Toit Ouvert',
    'containers.size.20ft': '20 Pieds',
    'containers.size.40ft': '40 Pieds',
    'containers.viewDetails': 'Voir Détails',
    'containers.editContainer': 'Modifier Conteneur',
    'containers.auditLog': 'Journal d\'Audit',
    'containers.damage.reports': 'Rapports de Dommages',
    'containers.damage.none': 'Aucun rapport de dommage enregistré',
    'containers.damage.add': 'Ajouter Rapport de Dommage',
    'containers.damage.describe': 'Décrire les dommages...',
    'containers.export.csv': 'Exporter CSV',
    'containers.export.excel': 'Exporter Excel',
    'containers.export.html': 'Exporter HTML',
    'containers.export.button': 'Exporter',
    'containers.list.noContainers': 'Aucun conteneur trouvé',
    'containers.list.noContainersClient': 'Aucun conteneur trouvé pour votre entreprise. Contactez le dépôt si vous vous attendez à voir des conteneurs ici.',
    'containers.table.gateIn': 'Entrée',
    'containers.table.gateOut': 'Sortie',
    'containers.table.fullEmpty': 'Plein / Vide',
    'containers.table.damagesReported': 'dommage(s) signalé(s)',
    'containers.table.container': 'Conteneur',
    'containers.filter.from': 'Du',
    'containers.filter.to': 'Au',
    'containers.filter.filterByClient': 'Filtrer par client...',
    'containers.filter.allStatus': 'Tous les statuts',
    'containers.stats.yourContainers': 'Vos Conteneurs',
    'containers.stats.withDamage': 'Endommagés',
    'containers.details.title': 'Détails du Conteneur',
    'containers.details.statusType': 'Détails Statut & Type',
    'containers.details.yourCompany': 'Votre Entreprise',
    'containers.details.days': 'jours',
    'containers.edit.steps.location': 'Affectation d\'Emplacement',
    'containers.edit.steps.damage': 'Évaluation des Dommages',
    'containers.edit.steps.review': 'Réviser & Confirmer',
    'containers.edit.validationErrors': 'Erreurs de Validation :',
    'containers.edit.validating': 'Validation...',
    'containers.edit.noPermission': 'Vous n\'avez pas la permission de modifier les conteneurs.',
    'containers.delete.title': 'Supprimer le Conteneur',
    'containers.delete.confirmMessage': 'Cela marquera le conteneur comme supprimé.',
    'containers.delete.success': 'Conteneur supprimé avec succès !',
    'containers.update.success': 'Conteneur mis à jour avec succès !',
    'containers.delete.blocked': 'Impossible de supprimer ce conteneur :',
    'containers.delete.actionRequired': 'Action Requise :',

    // Gate Operations
    'gate.in.title': 'Gestion des Entrées',
    'gate.in.new': 'Nouvelle Entrée',
    'gate.in.pending': 'Opérations en Attente',
    'gate.in.completed': 'Opérations Terminées',
    'gate.in.stats.today': 'Entrées d\'Aujourd\'hui',
    'gate.in.stats.pending': 'Opérations en Attente',
    'gate.in.stats.processed': 'Conteneurs Traités',
    'gate.in.stats.damaged': 'Conteneurs Endommagés',
    'gate.in.form.containerInfo': 'Informations du Conteneur',
    'gate.in.form.transportInfo': 'Informations de Transport',
    'gate.in.form.timeTracking': 'Suivi du Temps',
    'gate.in.form.containerNumber': 'Numéro de Conteneur',
    'gate.in.form.containerSize': 'Taille du Conteneur',
    'gate.in.form.containerType': 'Type de Conteneur',
    'gate.in.form.quantity': 'Quantité',
    'gate.in.form.status': 'Statut du Conteneur',
    'gate.in.form.damage': 'Statut des Dommages',
    'gate.in.form.client': 'Client',
    'gate.in.form.booking': 'Référence de Réservation',
    'gate.in.form.driver': 'Nom du Chauffeur',
    'gate.in.form.truck': 'Numéro de Camion',
    'gate.in.form.transport': 'Entreprise de Transport',
    'gate.in.form.arrivalDate': 'Date d\'Arrivée',
    'gate.in.form.arrivalTime': 'Heure d\'Arrivée',
    'gate.in.form.highCube': 'Est-ce un High Cube ?',
    'gate.in.form.equipmentRef': 'Référence Équipement',
    'gate.in.form.searchClient': 'Rechercher un client par nom ou code...',
    'gate.in.form.arrival': 'Heure d\'Arrivée du Camion',
    'gate.in.validation.required': 'Ce champ est obligatoire',
    'gate.in.validation.containerFormat': 'Format de numéro de conteneur invalide',
    'gate.in.validation.validFormat': 'Format valide',

    'gate.out.title': 'Gestion des Sorties',
    'gate.out.new': 'Nouvelle Sortie',
    'gate.out.pending': 'Opérations en Attente',
    'gate.out.stats.today': 'Sorties d\'Aujourd\'hui',
    'gate.out.stats.pending': 'Opérations en Attente',
    'gate.out.stats.processed': 'Conteneurs Traités',
    'gate.out.stats.issues': 'Problèmes Signalés',
    'gate.out.form.booking': 'Sélection de Réservation',
    'gate.out.form.transport': 'Informations de Transport',
    'gate.out.form.containers': 'Numéros de Conteneurs',
    'gate.out.form.selectBooking': 'Sélectionner Réservation',
    'gate.out.form.driver': 'Nom du Chauffeur',
    'gate.out.form.vehicle': 'Numéro de Véhicule',
    'gate.out.form.company': 'Entreprise de Transport',
    'gate.out.form.vehicleNumberError': 'Le camion {truck} a une opération en attente en cours. Veuillez terminer ou annuler l\'opération existante avant de continuer.',
    'gate.out.completion.submit': 'Terminer la Sortie',
    'gate.out.truckRules.title': 'Règles de Capacité Camion',
    'gate.out.truckRules.40ft': 'Maximum 1 conteneur de 40 pieds par camion',
    'gate.out.truckRules.20ft': 'Maximum 2 conteneurs de 20 pieds par camion',
    'gate.out.truckRules.mix': 'Impossible de mélanger 20 pieds et 40 pieds',
    'gate.out.truckRules.disabled40ft': 'Désactivé (camion 40 pieds plein)',
    'gate.out.error.containerNotFound': 'Conteneur non trouvé dans la cour',
    'gate.out.error.invalidStatus': 'Statut invalide : {status}',
    'gate.out.success.validated': 'Conteneur Validé',
    'gate.out.completion.containers': 'Numéros de Conteneurs',
    'gate.out.completion.confirm': 'Confirmer le Numéro de Conteneur',
    'gate.out.completion.gateOutTime': 'Date et Heure de Sortie',
    'gate.in.subtitle': 'Gestion des entrées de conteneurs',
    'gate.in.search': 'Rechercher des opérations...',
    'gate.in.stats.alimentaire': 'Conteneurs Alimentaires',
    'gate.in.success': 'Opération d\'entrée terminée avec succès',
    'gate.in.summary': 'Résumé de l\'opération',
    'gate.in.pendingNotice.title': 'Opération en attente',
    'gate.in.pendingNotice.desc': 'Cette opération d\'entrée sera créée avec le statut En attente. L\'attribution de la pile et l\'évaluation des dommages seront effectuées plus tard.',
    'gate.out.subtitle': 'Gestion des sorties de conteneurs',
    'gate.out.summary': 'Résumé de l\'opération',
    'gate.out.form.searchBooking': 'Rechercher et sélectionner une réservation...',
    'gate.out.form.selectedBooking': 'Réservation sélectionnée',
    'gate.out.form.selectBookingMessage': 'Veuillez sélectionner une réservation pour continuer.',
    'common.fixErrors': 'Veuillez corriger les erreurs suivantes :',
    'common.pleaseReview': 'Veuillez vérifier :',
    'common.submissionFailed': 'Échec de la soumission',

    // Release Orders
    'releases.title': 'Ordres de Sortie',
    'releases.booking.title': 'Gestion des Réservations',
    'releases.create': 'Créer un Ordre',
    'releases.createBooking': 'Créer une Réservation',
    'releases.pending': 'En Attente de Validation',
    'releases.validated': 'Validés',
    'releases.executed': 'Exécutés',
    'releases.completed': 'Terminés',
    'releases.cancelled': 'Annulés',
    'releases.inProcess': 'En Cours',
    'releases.stats.total': 'Total Réservations',
    'releases.stats.pending': 'En Attente',
    'releases.stats.validated': 'Validées',
    'releases.stats.completed': 'Terminées',
    'releases.form.bookingInfo': 'Informations de Réservation',
    'releases.form.clientInfo': 'Informations Client',
    'releases.form.quantities': 'Quantités de Conteneurs',
    'releases.form.bookingNumber': 'Numéro de Référence de Réservation',
    'releases.form.bookingType': 'Type de Réservation',
    'releases.form.client': 'Sélectionner Client',
    'releases.form.threshold': 'Seuil de Quantité Maximum',
    'releases.form.containers20': 'Conteneurs 20"',
    'releases.form.containers40': 'Conteneurs 40"',
    'releases.form.notes': 'Notes',
    'releases.breakdown.required': 'Répartition détaillée requise',
    'releases.breakdown.summary': 'Résumé des Conteneurs',
    'releases.subtitle': 'Ordres de sortie et réservations de conteneurs',
    'releases.search': 'Rechercher des réservations...',
    'releases.subtitle.edit': 'Mettre à jour la référence de réservation',
    'releases.subtitle.create': 'Générer une nouvelle référence de réservation',
    'releases.form.bookingDesc': 'Définir le type de réservation et le numéro de référence',
    'releases.form.refImmutable': 'Le numéro de référence ne peut pas être modifié',
    'releases.form.refHelp': 'Ceci sera utilisé comme identifiant de réservation dans toute l\'application',
    'releases.form.clientDesc': 'Sélectionnez le client pour cette réservation',
    'releases.form.qtyControl': 'Contrôle de Quantité',
    'releases.form.qtyControlDesc': 'Définir les limites pour l\'allocation des conteneurs',
    'releases.form.thresholdHelp': 'Nombre maximum de conteneurs autorisés avant de nécessiter une répartition détaillée par taille',
    'releases.form.quantitiesTitle': 'Quantités de Conteneurs par Taille',
    'releases.breakdown.help': 'Le total dépasse le seuil. Une répartition détaillée sera requise pour le traitement.',
    'gate.out.stats.remaining': 'Conteneurs Restants',
    'common.createdBy': 'Créé par',
    'common.createdDate': 'Date de Création',
    'common.updatedDate': 'Date de Modification',
    'common.standard': 'Standard',
    'common.highCapacity': 'Haute Capacité',
    'common.summary': 'Résumé',

    // Yard Management
    'yard.title': 'Gestion de Cour',
    'yard.loading': 'Chargement de la gestion de cour...',
    'yard.noYardSelected': 'Aucune cour sélectionnée',
    'yard.selectYardMessage': 'Veuillez sélectionner une cour pour continuer',
    'yard.search': 'Recherche de Conteneurs',
    'yard.searchContainer': 'Rechercher et Localiser',
    'yard.selectedContainer': 'Conteneur Sélectionné',
    'yard.resetView': 'Réinitialiser à la Vue Complète de la Cour',
    'yard.resetViewShort': 'Réinitialiser la vue',
    'yard.occupancy': 'Occupation',
    'yard.capacity': 'Capacité',
    'yard.utilization': 'Utilisation',
    'yard.sections': 'Sections',
    'yard.stacks': 'Total des Piles',
    'yard.stackCapacity': 'Capacité Totale des Piles',
    'yard.containersVisible': 'conteneurs visibles',
    'yard.selected': 'sélectionné',
    'yard.zoomIn': 'Zoom avant',
    'yard.zoomOut': 'Zoom arrière',
    'yard.showLegend': 'Afficher la légende',
    'yard.hideLegend': 'Masquer la légende',
    'yard.legend.title': 'Légende',
    'yard.legend.tips': 'Conseils :',
    'yard.legend.tip1': 'Cliquez sur les conteneurs pour sélectionner',
    'yard.legend.tip2': 'Clic droit + glisser pour déplacer',
    'yard.legend.tip3': 'Défiler pour zoomer',
    'yard.legend.availableSlot': 'Emplacement disponible',
    'yard.legend.availableSlotDesc': 'Position de conteneur vide',
    'yard.legend.containerInDepot': 'Conteneur au dépôt',
    'yard.legend.containerInDepotDesc': 'Conteneur stocké dans la cour',
    'yard.legend.underMaintenance': 'En maintenance',
    'yard.legend.underMaintenanceDesc': 'Conteneur en cours de réparation',
    'yard.legend.beingCleaned': 'En nettoyage',
    'yard.legend.beingCleanedDesc': 'Conteneur en cours de nettoyage',
    'yard.legend.damagedContainer': 'Conteneur endommagé',
    'yard.legend.damagedContainerDesc': 'Conteneur avec rapports de dommages',
    'yard.legend.selectedContainer': 'Conteneur sélectionné',
    'yard.legend.selectedContainerDesc': 'Conteneur actuellement sélectionné',
    'yard.stats.title': 'Statistiques de la cour',
    'yard.stats.activeContainers': 'Conteneurs actifs',
    'yard.stats.maintenance': 'En maintenance',
    'yard.stats.cleaning': 'En nettoyage',
    'yard.stats.damaged': 'Endommagé',
    'yard.stats.totalStacks': 'Total des Piles',
    'yard.info.title': 'Informations sur la cour',
    'yard.info.layout': 'Disposition :',
    'yard.info.sections': 'Sections :',
    'yard.info.totalCapacity': 'Capacité totale :',
    'yard.info.currentOccupancy': 'Occupation actuelle :',

    // Depot Management
    'depot.title': 'Gestion des Dépôts',
    'depot.create': 'Créer un Dépôt',
    'depot.edit': 'Modifier le Dépôt',
    'depot.view': 'Voir les Détails',
    'depot.assign': 'Assigner des Utilisateurs',
    'depot.delete': 'Supprimer le Dépôt',
    'depot.stats.total': 'Total des Dépôts',
    'depot.stats.active': 'Dépôts Actifs',
    'depot.stats.capacity': 'Capacité Totale',
    'depot.stats.occupancy': 'Occupation Totale',
    'depot.form.basicInfo': 'Informations de Base',
    'depot.form.contactInfo': 'Informations de Contact',
    'depot.form.address': 'Informations d\'Adresse',
    'depot.form.name': 'Nom du Dépôt',
    'depot.form.code': 'Code du Dépôt',
    'depot.form.description': 'Description',
    'depot.form.location': 'Emplacement',
    'depot.form.capacity': 'Capacité Totale',
    'depot.form.layout': 'Type de Disposition',
    'depot.form.manager': 'Nom du Gestionnaire',
    'depot.form.phone': 'Téléphone',
    'depot.form.email': 'Email',
    'depot.form.street': 'Adresse de la Rue',
    'depot.form.city': 'Ville',
    'depot.form.state': 'État/Région',
    'depot.form.zipCode': 'Code Postal',
    'depot.form.country': 'Pays',
    'depot.form.timezone': 'Fuseau Horaire',
    'depot.form.status': 'Statut',
    'depot.layout.yirima': 'Grille Yirima',
    'depot.layout.tantarelli': 'Disposition Tantarelli',

    // Stack Management
    'stack.title': 'Gestion des Piles',
    'stack.subtitle': 'Configurer les affectations de taille de conteneur pour toutes les piles',
    'stack.configuration': 'Configuration des Piles',
    'stack.configuration.desc': 'Configurer les affectations de taille de conteneur pour chaque pile (les piles jumelées seront mises à jour ensemble)',
    'stack.create': 'Créer une Pile',
    'stack.edit': 'Modifier la Pile',
    'stack.delete': 'Supprimer la Pile',
    'stack.refresh': 'Actualiser',
    'stack.refreshing': 'Actualisation...',
    'stack.rules': 'Règles de Configuration',
    'stack.pairing': 'Paires de Piles Valides pour Conteneurs 40ft',
    'stack.search': 'Rechercher des piles ou sections...',
    'stack.size20': '20ft',
    'stack.size40': '40ft',
    'stack.special': 'Spéciale',
    'stack.regular': 'Régulière',
    'stack.assigned': 'Client Assigné',
    'stack.unassigned': 'Non Assignée',
    'stack.exclusive': 'Exclusif',
    'stack.shared': 'Partagé',
    'stack.saveChanges': 'Sauvegarder les Modifications',
    'stack.resetChanges': 'Réinitialiser',
    'stack.rules.special': 'Piles Spéciales (01, 31, 101, 103) : Ne peuvent être configurées que pour des conteneurs de 20 pieds.',
    'stack.rules.regular': 'Piles Régulières : Peuvent être configurées pour des conteneurs de 20 ou 40 pieds.',
    'stack.rules.pairing': 'Attribution 40 pieds : Disponible uniquement pour les piles régulières qui ont une pile régulière adjacente pour former des paires valides.',
    'stack.rules.updates': 'Mises à jour Appariées : Lors du changement d\'une pile régulière vers 40 pieds, sa paire adjacente sera automatiquement mise à jour pour correspondre.',
    'stack.refreshed': 'Configuration des piles actualisée avec succès !',
    'stack.delete.title': 'Suppression logicielle de la pile',
    'stack.delete.confirm': 'Êtes-vous sûr de vouloir supprimer logiquement la pile S{number} ? Cela désactivera la pile et tous ses emplacements, mais préservera toutes les données pour une récupération potentielle. Vous pourrez la réactiver plus tard si nécessaire.',
    'stack.delete.success': 'Pile S{number} supprimée logiquement avec succès ! Vous pouvez la réactiver plus tard si nécessaire.',
    'stack.delete.error': 'Échec de la suppression logicielle de la pile',
    'stack.update.success': 'Pile mise à jour avec succès !',
    'stack.create.success': 'Pile créée avec succès !',
    'stack.sizeUpdate.success': 'Pile mise à jour en {size} avec succès !',
    'stack.sizeUpdate.successMulti': 'Mise à jour réussie de {count} piles en {size} !',
    'stack.sizeUpdate.errorOccupied': 'Impossible de changer la taille de la pile : les emplacements de pile virtuelle sont occupés. Veuillez d\'abord déplacer tous les conteneurs des piles jumelées.',
    'stack.assign.success': 'Pile assignée au client {client} avec succès !',
    'stack.unassigned.success': 'Pile désassignée du pool client avec succès !',
    'stack.noStacks': 'Aucune pile trouvée. Créez votre première pile pour commencer.',
    'stack.stats.total': 'Total des Piles',
    'stack.stats.40ft': 'Total des Piles 40ft',
    'stack.stats.20ft': 'Total des Piles 20ft',
    'stack.stats.special': 'Piles Spéciales',
    'stack.stats.regular': 'Piles Régulières',
    'stack.stats.clientAssigned': 'Assigné au Client',
    'stack.stats.all': 'Toutes les piles',
    'stack.stats.logicalPairs': 'Paires logiques',
    'stack.stats.single': 'Piles simples',
    'stack.stats.buffer': 'Zones tampons',
    'stack.stats.standardOps': 'Opérations standard',
    'stack.stats.unassignedCount': '{count} non assignées',
    'stack.table.stack': 'Pile',
    'stack.table.section': 'Section',
    'stack.table.containerSize': 'Taille de Conteneur',
    'stack.table.assignedClient': 'Client Assigné',
    'stack.table.capacity': 'Capacité',
    'stack.table.actions': 'Actions',
    'stack.table.manage': 'Gérer',
    'stack.table.pair': 'Paire',
    'stack.table.noPair': 'Pas de paire',
    'stack.table.specialNo40': 'Les piles spéciales ne peuvent pas être configurées pour 40ft',
    'stack.table.updatePair': 'Mettra également à jour la Pile {number}',
    'stack.advancedFilter': 'Filtre Avancé',
    'stack.allStacks': 'Toutes les Piles',
    'stack.allSections': 'Toutes les Sections',
    'stack.help.title': 'Aide à la Configuration des Piles',
    'stack.help.desc': 'Afficher les règles et directives pour la gestion des piles de la cour.',
    'stack.loadingConfig': 'Veuillez patienter pendant que nous chargeons la configuration de la cour.',
    'stack.form.information': 'Informations de la Pile',
    'stack.form.number': 'Numéro de Pile',
    'stack.form.section': 'Section',
    'stack.form.sizeConfig': 'Configuration de la Taille du Conteneur',
    'stack.form.typeConfig': 'Configuration du Type de Pile',
    'stack.form.capacityConfig': 'Configuration de la Capacité',
    'stack.form.dimensions': 'Dimensions de la Pile',
    'stack.form.dimensionsDesc': 'Configurer la disposition physique de votre pile',
    'stack.form.rows': 'Rangées (Profondeur)',
    'stack.form.tiers': 'Paliers Max (Hauteur)',
    'stack.form.customTiers': 'Configuration Personnalisée des Paliers',
    'stack.form.preview': 'Aperçu de la Pile',
    'stack.form.useSuggested': 'Utiliser {number}',
    'stack.form.suggested': 'Suggéré : {number}',
    'stack.form.differentFromSuggested': 'Différent du suggéré',
    'stack.form.usingSuggested': 'Utilise le suggéré',
    'stack.form.selectSection': 'Sélectionner la section',
    'stack.form.noSections': 'Aucune section disponible',
    'stack.form.sectionImmutable': 'La section ne peut pas être modifiée lors de l\'édition d\'une pile existante',
    'stack.form.20ftDesc': 'Taille Standard',
    'stack.form.40ftDesc': 'Haute Capacité',
    'stack.form.specialWarning': 'Les piles spéciales sont limitées aux conteneurs de 20 pieds uniquement',
    'stack.form.regularDesc': 'Opérations Standard',
    'stack.form.specialDesc': 'Opérations Limitées',
    'stack.form.rowsDesc': 'Rangées de conteneurs de l\'avant vers l\'arrière',
    'stack.form.tiersDesc': 'Maximum de conteneurs empilés verticalement',
    'stack.form.customTiersDesc': 'Configurer différentes hauteurs de paliers maximales pour chaque rangée en fonction des conditions du sol ou des limitations de l\'équipement',
    'stack.form.previewLayout': 'Aperçu de la Disposition de la Pile',
    'stack.form.totalCapacity': 'Capacité Totale de la Pile',
    'stack.form.capacityDesc': 'Positions maximales de conteneurs disponibles',
    'stack.form.positions': 'Positions de conteneurs',
    'stack.form.uniformLayout': 'Disposition uniforme',
    'stack.form.customLayout': 'Disposition personnalisée',
    'stack.form.calculation': 'Calcul',
    'stack.form.specialNotice': 'Cette pile sera limitée aux conteneurs de 20 pieds uniquement et ne pourra pas accueillir de conteneurs de 40 pieds.',
    'stack.form.40ftNotice': 'Cette pile sera configurée pour des conteneurs 40 pieds de haute capacité et peut nécessiter un jumelage avec des piles adjacentes.',
    'stack.validation.numberRequired': 'Le numéro de pile doit être supérieur à 0',
    'stack.validation.sectionRequired': 'La section est requise',
    'stack.validation.rowsRange': 'Les rangées doivent être comprises entre 1 et 10',
    'stack.validation.tiersRange': 'Les paliers max doivent être compris entre 1 et 8',
    'stack.validation.specialNo40': 'Les piles spéciales ne peuvent accueillir que des conteneurs de 20 pieds',
    'stack.validation.rowChangeError': 'Impossible de valider le changement de rangée. Veuillez réessayer.',


    'depot.subtitle': 'Gérer les dépôts de conteneurs et leurs configurations',
    'depot.search': 'Rechercher des dépôts...',
    'depot.overview': 'Aperçu des Dépôts',
    'depot.noDepots': 'Aucun dépôt trouvé',
    'depot.noDepotsEmpty': 'Aucun dépôt n\'a encore été créé.',
    'depot.delete.confirm': 'Êtes-vous sûr de vouloir supprimer le dépôt "{name}" ? Cette action est irréversible.',
    'depot.delete.success': 'Dépôt "{name}" supprimé avec succès !',
    'depot.delete.errorCurrent': 'Impossible de supprimer le dépôt actuellement sélectionné. Veuillez d\'abord passer à un autre dépôt.',


    // Client Pools
    'clientPools.title': 'Gestion des Pools Clients',
    'clientPools.create': 'Créer un Pool Client',
    'clientPools.edit': 'Modifier le Pool Client',
    'clientPools.stats.total': 'Total des Pools',
    'clientPools.stats.active': 'Clients Actifs',
    'clientPools.stats.stacks': 'Piles Assignées',
    'clientPools.stats.utilization': 'Utilisation Moyenne',
    'clientPools.form.clientInfo': 'Informations Client',
    'clientPools.form.stackAssignment': 'Attribution des Piles',
    'clientPools.form.additionalInfo': 'Informations Supplémentaires',
    'clientPools.form.selectClient': 'Sélectionner un Client',
    'clientPools.form.contractStart': 'Date de Début de Contrat',
    'clientPools.form.contractEnd': 'Date de Fin de Contrat',
    'clientPools.form.notes': 'Notes et Instructions Spéciales',
    'clientPools.form.capacity': 'Capacité',
    'clientPools.form.selected': 'Sélectionnées',
    'clientPools.form.stacks': 'piles',
    'clientPools.form.containers': 'conteneurs',
    'clientPools.priority.high': 'Élevée',
    'clientPools.priority.medium': 'Moyenne',
    'clientPools.priority.low': 'Faible',
    'clientPools.subtitle': 'Gérer les attributions de piles spécifiques aux clients et l\'allocation de capacité',
    'clientPools.search': 'Rechercher des pools clients...',
    'clientPools.overview': 'Aperçu du Pool Client',
    'clientPools.table.stacks': 'piles',
    'clientPools.table.viewStacks': 'Voir détails des piles →',
    'clientPools.noPools': 'Aucun pool client trouvé',
    'clientPools.noPoolsEmpty': 'Aucun pool client n\'a encore été créé.',
    'clientPools.delete.title': 'Supprimer le Pool Client',
    'clientPools.delete.confirm': 'Êtes-vous sûr de vouloir supprimer le pool pour {client} ? Cette action est irréversible.',
    'clientPools.utilization.title': 'Aperçu de l\'Utilisation du Pool',
    'clientPools.form.subtitle.edit': 'Mettre à jour la configuration du pool client',
    'clientPools.form.subtitle.create': 'Assigner des piles dédiées à un client',
    'clientPools.form.selectClientPlaceholder': 'Sélectionner un client...',
    'clientPools.form.selectStacks': 'Sélectionner Piles',
    'clientPools.form.modifySelection': 'Modifier la Sélection',
    'clientPools.form.noStacks': 'Aucune Pile Sélectionnée',
    'clientPools.form.noStacksHelp': 'Cliquez sur le bouton ci-dessus pour sélectionner des piles pour ce pool client',
    'clientPools.form.noAvailableStacks': 'Aucune Pile Disponible',
    'clientPools.form.noAvailableStacksHelp': 'Toutes les piles sont actuellement assignées à d\'autres clients',
    'clientPools.form.progress.client': 'Client Sélectionné',
    'clientPools.form.progress.stacks': 'Piles Assignées',
    'clientPools.form.progress.contract': 'Date de Contrat Définie',
    'clientPools.stackSelection.title': 'Sélectionner des Piles pour le Pool Client',
    'clientPools.stackSelection.subtitle': 'Choisissez des piles à assigner à {client} (Piles physiques uniquement - piles virtuelles assignées automatiquement)',

    // Client Master Data
    'clients.title': 'Données Maîtres Clients',
    'clients.add': 'Ajouter un Client',
    'clients.edit': 'Modifier le Client',
    'clients.view': 'Voir les Détails',
    'clients.delete': 'Supprimer le Client',
    'clients.stats.total': 'Total Clients',
    'clients.stats.active': 'Clients Actifs',
    'clients.stats.creditLimit': 'Limite de Crédit Totale',
    'clients.stats.avgPayment': 'Conditions de Paiement Moyennes',
    'clients.form.basicInfo': 'Informations de Base',
    'clients.form.address': 'Adresse de l\'Entreprise',
    'clients.form.contact': 'Personne de Contact',
    'clients.form.billing': 'Adresse de Facturation',
    'clients.form.financial': 'Configuration Financière',
    'clients.form.name': 'Nom de l\'Entreprise',
    'clients.form.code': 'Code Client',
    'clients.search': 'Rechercher des clients...',
    'clients.noClients': 'Aucun client trouvé',
    'clients.noClientsEmpty': 'Commencez par ajouter votre premier client.',
    'clients.delete.title': 'Supprimer le Client',
    'clients.delete.confirm': 'Êtes-vous sûr de vouloir supprimer {client} ? Cette action est irréversible.',
    'clients.success.update': 'Client mis à jour avec succès !',
    'clients.success.create': 'Client créé avec succès !',
    'clients.success.delete': 'Client supprimé avec succès !',
    'clients.error.save': 'Erreur lors de l\'enregistrement du client :',
    'clients.table.contact': 'Informations de Contact',
    'clients.form.subtitle.edit': 'Modification du client {client}',
    'clients.form.subtitle.create': 'Création d\'un nouveau client',
    'clients.form.step.basic': 'Informations de base',
    'clients.form.step.address': 'Adresse & Contact',
    'clients.form.step.config': 'Configuration',
    'clients.form.companyName': 'Nom de l\'Entreprise',
    'clients.form.mainEmail': 'Email Principal',
    'clients.form.mainPhone': 'Téléphone Principal',
    'clients.form.taxId': 'Numéro d\'Identification Fiscale',
    'clients.form.addressTitle': 'Adresse de l\'Entreprise',
    'clients.form.addressDesc': 'Localisation et coordonnées de l\'entreprise',
    'clients.form.street': 'Adresse Complète',
    'clients.form.city': 'Ville',
    'clients.form.district': 'Commune/District',
    'clients.form.zipCode': 'Code Postal',
    'clients.form.country': 'Pays',
    'clients.form.contactTitle': 'Personne de Contact',
    'clients.form.contactDesc': 'Responsable principal pour les communications',
    'clients.form.contactName': 'Nom Complet',
    'clients.form.contactPosition': 'Poste/Fonction',
    'clients.form.contactEmail': 'Email de Contact',
    'clients.form.contactPhone': 'Téléphone de Contact',
    'clients.form.billingTitle': 'Adresse de Facturation',
    'clients.form.billingDesc': 'Adresse pour l\'envoi des factures',
    'clients.form.sameAddress': 'Même adresse que l\'entreprise',
    'clients.form.financialTitle': 'Configuration Financière',
    'clients.form.financialDesc': 'Paramètres de facturation et conditions de paiement',
    'clients.form.creditLimit': 'Limite de Crédit',
    'clients.form.paymentTerms': 'Conditions de Paiement (jours)',
    'clients.form.freeDays': 'Jours de Stockage Gratuits',
    'clients.form.dailyRate': 'Tarif Journalier',
    'clients.form.currency': 'Devise',
    'clients.form.previewTitle': 'Aperçu de la Facturation',
    'clients.form.previewDesc': 'Simulation des coûts de stockage',
    'clients.form.freeDaysLabel': 'Jours Gratuits',
    'clients.form.rateLabel': 'Tarif/Jour',
    'clients.form.termsLabel': 'Jours de Paiement',
    'clients.form.calculationExample': 'Exemple de calcul :',
    'clients.form.exampleTenDays': 'Conteneur placé pendant 10 jours',
    'clients.form.exampleFreeDays': 'Jours gratuits :',
    'clients.form.exampleBillable': 'Jours facturables :',
    'clients.form.exampleTotal': 'Montant total :',
    'clients.form.notesTitle': 'Notes et Instructions Spéciales',
    'clients.form.notesDesc': 'Informations complémentaires et instructions particulières',
    'clients.form.systemTitle': 'Configuration Système',
    'clients.form.systemDesc': 'Paramètres système et intégrations',
    'clients.form.activeLabel': 'Client Actif',
    'clients.form.activeDesc': 'Le client peut effectuer des opérations',
    'clients.form.autoEdiLabel': 'Transmission EDI Automatique',
    'clients.form.autoEdiDesc': 'Envoi automatique des messages CODECO',
    'clients.form.ediActive': 'Transmission EDI activée :',
    'clients.form.notes': 'Notes et Instructions Spéciales',
    'clients.form.active': 'Client Actif',

    // User Management
    'users.title': 'Gestion des Utilisateurs',
    'users.add': 'Ajouter un Utilisateur',
    'users.edit': 'Modifier l\'Utilisateur',
    'users.view': 'Voir les Détails',
    'users.delete': 'Supprimer l\'Utilisateur',
    'users.stats.total': 'Total des Utilisateurs',
    'users.stats.active': 'Utilisateurs Actifs',
    'users.stats.admins': 'Administrateurs',
    'users.stats.online': 'En Ligne Aujourd\'hui',
    'users.form.basicInfo': 'Informations de base',
    'users.form.name': 'Nom complet',
    'users.form.email': 'Adresse e-mail',
    'users.form.phone': 'Numéro de téléphone',
    'users.form.department': 'Département',
    'users.form.company': 'Entreprise',
    'users.form.password': 'Mot de passe',
    'users.form.role': 'Rôle de l\'utilisateur',
    'users.form.active': 'Utilisateur Actif',
    'users.role.admin': 'Administrateur',
    'users.subtitle.managing': 'Gestion des utilisateurs pour :',
    'users.search': 'Rechercher des utilisateurs...',
    'users.noUsers': 'Aucun utilisateur trouvé',
    'users.noUsersEmpty': 'Commencez par ajouter votre premier utilisateur',
    'users.delete.title': 'Supprimer l\'Utilisateur',
    'users.delete.confirm': 'Êtes-vous sûr de vouloir supprimer {user} ? Cette action supprimera l\'utilisateur du système tout en préservant l\'intégrité des données.',
    'users.success.update': 'Utilisateur mis à jour avec succès',
    'users.success.create': 'Utilisateur créé avec succès',
    'users.success.delete': 'Utilisateur supprimé avec succès',
    'users.error.save': 'Échec de l\'enregistrement de l\'utilisateur',
    'users.error.delete': 'Échec de la suppression de l\'utilisateur',
    'users.table.user': 'Utilisateur',
    'users.table.role': 'Rôle',
    'users.table.department': 'Département',
    'users.table.lastLogin': 'Dernière Connexion',
    'users.form.subtitle.edit': 'Mettre à jour les informations et les permissions de l\'utilisateur',
    'users.form.subtitle.create': 'Ajouter un nouvel utilisateur au système',
    'users.form.status': 'Statut de l\'utilisateur',
    'users.form.profileInfo': 'Informations du profil',
    'users.form.permissionsOverview': 'Aperçu des permissions',
    'users.activity.recent': 'Activité récente',
    'users.activity.history': 'Historique de connexion',
    'users.validation.nameRequired': 'Le nom complet est requis',
    'users.validation.nameMin': 'Le nom doit comporter au moins 2 caractères',
    'users.validation.nameMax': 'Le nom doit comporter moins de 100 caractères',
    'users.validation.emailRequired': 'L\'adresse e-mail est requise',
    'users.validation.emailInvalid': 'Veuillez saisir une adresse e-mail valide',
    'users.validation.phoneInvalid': 'Veuillez saisir un numéro de téléphone valide',
    'users.validation.passwordRequired': 'Le mot de passe est requis pour les nouveaux utilisateurs',
    'users.validation.passwordMin': 'Le mot de passe doit comporter au moins 6 caractères',
    'users.validation.passwordMax': 'Le mot de passe doit comporter moins de 128 caractères',
    'users.role.description.admin': 'Accès complet au système dans tous les modules',
    'users.role.description.supervisor': 'Supervision et gestion des opérations',
    'users.role.description.operator': 'Opérations quotidiennes et manutention des conteneurs',
    'users.role.description.client': 'Consulter les conteneurs et créer des ordres de sortie',
    'common.time.never': 'Jamais',
    'common.time.justNow': 'À l\'instant',
    'common.time.hoursAgo': 'h',
    'common.time.daysAgo': 'j',
    'users.role.supervisor': 'Superviseur',
    'users.role.operator': 'Opérateur',
    'users.role.client': 'Client',
    'users.role.adminDesc': 'Accès complet au système sur tous les modules',
    'users.role.supervisorDesc': 'Supervision des opérations et gestion',
    'users.role.operatorDesc': 'Opérations quotidiennes et manipulation des conteneurs',
    'users.role.clientDesc': 'Voir les conteneurs et créer des ordres de libération',

    // Module Access
    'moduleAccess.title': 'Gestion des Accès aux Modules',
    'moduleAccess.bulkActions': 'Actions en Lot',
    'moduleAccess.applyRoleBased': 'Appliquer l\'Accès Basé sur le Rôle',
    'moduleAccess.enableAll': 'Activer Tout',
    'moduleAccess.disableAll': 'Désactiver Tout',
    'moduleAccess.selectAll': 'Sélectionner Tout',
    'moduleAccess.deselectAll': 'Désélectionner Tout',
    'moduleAccess.stats.totalUsers': 'Total des Utilisateurs',
    'moduleAccess.stats.modules': 'Modules Disponibles',
    'moduleAccess.stats.admins': 'Utilisateurs Admin',
    'moduleAccess.stats.selected': 'Utilisateurs Sélectionnés',
    'moduleAccess.category.core': 'Principal',
    'moduleAccess.category.operations': 'Opérations',
    'moduleAccess.category.management': 'Gestion',
    'moduleAccess.category.admin': 'Administration',
    'moduleAccess.roleRestricted': 'Restreint par Rôle',
    'moduleAccess.protected': 'Protégé',
    'moduleAccess.system': 'Système',

    // Reports & Analytics
    'reports.title': 'Rapports et Analyses',
    'reports.billing': 'Facturation et Jours Gratuits',
    'reports.analytics': 'Analyses',
    'reports.operations': 'Opérations',
    'reports.export': 'Exporter le Rapport',
    'reports.dateRange': 'Plage de Dates',
    'reports.startDate': 'Date de début',
    'reports.endDate': 'Date de fin',
    'reports.currentDepot': 'Dépôt Actuel',
    'reports.allDepots': 'Tous les Dépôts',
    'reports.globalView': 'Vue Globale',
    'reports.billing.title': 'Détails de Facturation des Conteneurs',
    'reports.billing.freeDays': 'Calcul des jours gratuits et informations de facturation',
    'reports.billing.totalRevenue': 'Revenus Totaux',
    'reports.billing.activeContainers': 'Conteneurs Actifs',
    'edi.title': 'Gestion EDI',
    'edi.subtitle': 'Gérer les transmissions EDI, les configurations de serveur et les paramètres client',
    'edi.configuration': 'Configuration',
    'edi.tabs.overview': 'Aperçu',
    'edi.tabs.servers': 'Serveurs FTP/SFTP',
    'edi.tabs.clients': 'Paramètres EDI Client',
    'edi.tabs.validator': 'Validateur EDI',
    'edi.tabs.history': 'Historique des Transmissions',
    'edi.stats.total': 'Opérations Totales',
    'edi.stats.success': 'Taux de Succès EDI',
    'edi.stats.clients': 'Clients avec EDI',
    'edi.stats.servers': 'Serveurs Configurés',
    'edi.recentOperations': 'Opérations EDI Récentes',
    'edi.servers.title': 'Configuration Serveur FTP/SFTP',
    'edi.servers.configure': 'Configurer les Serveurs',
    'edi.servers.emptyAction': 'Configurer votre premier serveur',
    'edi.clients.title': 'Paramètres EDI Client',
    'edi.clients.empty': 'Aucun client configuré pour l\'EDI',
    'edi.clients.emptyAction': 'Configurer votre premier client',
    'edi.history.title': 'Historique des Transmissions',
    'edi.history.empty': 'Aucun journal de transmission trouvé',
    'edi.history.table.container': 'Conteneur',
    'edi.history.table.operation': 'Opération',
    'edi.history.table.status': 'Statut',
    'edi.history.table.client': 'Client',
    'edi.history.table.date': 'Date de Transmission',
    'edi.error.load': 'Échec du chargement des données EDI',
    'edi.success.refresh': 'Données actualisées avec succès',
    'edi.success.retry': 'Nouvelle tentative de transmission initiée',
    'edi.error.retry': 'Échec de la nouvelle tentative',
    'edi.success.clientDelete': 'Configuration EDI client supprimée',
    'edi.error.clientDelete': 'Échec de la suppression de la configuration EDI client',
    'edi.success.clientSave': 'Configuration EDI client enregistrée',
    'edi.delete.confirm': 'Êtes-vous sûr de vouloir supprimer la configuration EDI pour ce client ?',
    'edi.configModal.title': 'Configuration EDI',
    'edi.configModal.listTitle': 'Configurations',
    'edi.configModal.form.name': 'Nom de la Configuration',
    'edi.configModal.form.type': 'Type de Serveur',
    'edi.configModal.form.host': 'Hôte',
    'edi.configModal.form.port': 'Port',
    'edi.configModal.form.username': 'Nom d\'utilisateur',
    'edi.configModal.form.password': 'Mot de passe',
    'edi.configModal.form.remotePath': 'Chemin Distant',
    'edi.configModal.form.partnerCode': 'Code Partenaire',
    'edi.configModal.form.senderCode': 'Code Expéditeur',
    'edi.configModal.form.timeout': 'Délai d\'attente (ms)',
    'edi.configModal.form.retry': 'Tentatives de Recommencement',
    'edi.configModal.form.filePattern': 'Modèle de Nom de Fichier',
    'edi.configModal.form.assignedClients': 'Clients Assignés',
    'edi.configModal.form.noClients': 'Aucun client assigné',
    'edi.configModal.form.searchPlaceholder': 'Rechercher ou ajouter un client...',
    'edi.configModal.form.addCustom': 'Ajouter "{client}"',
    'edi.configModal.emptyTitle': 'Aucune Configuration Sélectionnée',
    'edi.configModal.emptyDesc': 'Sélectionnez une configuration dans la liste pour voir les détails, ou créez-en une nouvelle.',
    'edi.configModal.form.testMode': 'Mode Test',
    'edi.configModal.form.testModeDesc': 'En mode test, les transmissions sont simulées et aucun fichier réel n\'est téléchargé.',
    'edi.configModal.form.isDefault': 'Définir par défaut',
    'edi.configModal.form.testConnection': 'Tester la Connexion',
    'edi.configModal.form.passwordPlaceholder': 'Protégé',
    'edi.configModal.form.filePatternHint': 'Jetons : {timestamp}, {container}, {operation}, {client}',
    'edi.configModal.defaultLabel': 'Par défaut',
    'edi.clientModal.editTitle': 'Modifier la Configuration EDI Client',
    'edi.clientModal.createTitle': 'Ajouter une Configuration EDI Client',
    'edi.clientModal.form.enableEdi': 'Activer l\'EDI pour ce client',
    'edi.clientModal.form.enableIn': 'Activer l\'EDI Entrée (Gate In)',
    'edi.clientModal.form.enableOut': 'Activer l\'EDI Sortie (Gate Out)',
    'edi.checkAcknowledgments': 'Vérifier les Accusés de Réception',
    'edi.processFile': 'Traiter EDI à partir d\'un Fichier',
    'edi.fileType': 'Type de Fichier',
    'edi.operation': 'Opération',
    'edi.selectFile': 'Sélectionner un Fichier',
    'edi.processSend': 'Traiter et Envoyer',
    'edi.transmissionHistory': 'Historique des Transmissions',
    'edi.stats.sent': 'Total Envoyés',
    'edi.stats.pending': 'En Attente',
    'edi.stats.failed': 'Échoués',
    'edi.stats.acknowledged': 'Accusés de Réception',
    'edi.status.pending': 'En Attente',
    'edi.status.sent': 'Envoyé',
    'edi.status.failed': 'Échoué',
    'edi.status.acknowledged': 'Accusé de Réception',
    'edi.retry': 'Réessayer',
    'edi.view': 'Voir',

    // Common
    'common.status': 'Statut',
    'common.actions': 'Actions',
    'common.date': 'Date',
    'common.time': 'Heure',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.close': 'Fermer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.delete': 'Supprimer',
    'common.create': 'Créer',
    'common.update': 'Mettre à jour',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.export': 'Exporter',
    'common.import': 'Importer',
    'common.loading': 'Chargement...',
    'common.processing': 'Traitement...',
    'common.saving': 'Sauvegarde...',
    'common.updating': 'Mise à jour...',
    'common.creating': 'Création...',
    'common.deleting': 'Suppression...',
    'common.success': 'Succès',
    'common.error': 'Erreur',
    'common.warning': 'Avertissement',
    'common.info': 'Information',
    'common.required': 'Obligatoire',
    'common.optional': 'Optionnel',
    'common.active': 'Actif',
    'common.inactive': 'Inactif',
    'common.enabled': 'Activé',
    'common.disabled': 'Désactivé',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.all': 'Tout',
    'common.none': 'Aucun',
    'common.total': 'Total',
    'common.available': 'Disponible',
    'common.capacity': 'Capacité',
    'common.utilization': 'Utilisation',
    'common.location': 'Emplacement',
    'common.client': 'Client',
    'common.container': 'Conteneur',
    'common.containers': 'Conteneurs',
    'common.type': 'Type',
    'common.size': 'Taille',
    'common.quantity': 'Quantité',
    'common.notes': 'Notes',
    'common.description': 'Description',
    'common.name': 'Nom',
    'common.code': 'Code',
    'common.email': 'Email',
    'common.phone': 'Téléphone',
    'common.address': 'Adresse',
    'common.city': 'Ville',
    'common.country': 'Pays',
    'common.department': 'Département',
    'common.company': 'Entreprise',
    'common.role': 'Rôle',
    'common.permission': 'Permission',
    'common.access': 'Accès',
    'common.denied': 'Accès Refusé',
    'common.restricted': 'Accès Restreint',
    'common.unauthorized': 'Vous n\'avez pas la permission d\'accéder à ce module',
    'common.contactAdmin': 'Contactez votre administrateur pour demander l\'accès',
    'common.noData': 'Aucune donnée trouvée',
    'common.noResults': 'Aucun résultat trouvé',
    'common.tryAdjusting': 'Essayez d\'ajuster vos critères de recherche',
    'common.selectDate': 'Sélectionner une date',
    'common.selectTime': 'Sélectionner une heure',
    'common.currentTime': 'Heure actuelle',
    'common.today': 'Aujourd\'hui',
    'common.yesterday': 'Hier',
    'common.tomorrow': 'Demain',
    'common.thisWeek': 'Cette semaine',
    'common.thisMonth': 'Ce mois',
    'common.lastMonth': 'Le mois dernier',
    'common.thisYear': 'Cette année',
    'common.damaged': 'Endommagé',
    'common.undamaged': 'Bon état',
    'common.priority': 'Priorité',
    'common.urgent': 'Urgent',
    'common.normal': 'Normal',
    'common.low': 'Faible',
    'common.appSubtitle': 'Système de Gestion de Dépôt (SGD)',
    'common.loggedInAs': 'Connecté en tant que :',
    'common.install': 'Installer',
    'common.newNotifications': 'Nouveaux',
    'common.quickActions': 'Actions Rapides',
    'common.appFooter': 'Gestion de Dépôt de Conteneurs v1.0',
    'common.copyright': '© 2025 DepotManager',
    'dashboard.stats.vsLastMonth': 'vs mois dernier',
  }
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const useLanguageProvider = () => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return (translations[language] as any)[key] || key;
  };

  return {
    language,
    setLanguage,
    t
  };
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const languageState = useLanguageProvider();
  return <LanguageContext.Provider value={languageState}>{children}</LanguageContext.Provider>;
};

export { LanguageContext };
