import React, { useState, useEffect, useContext } from 'react';
import { Language } from '../types';
import { LanguageContext, LanguageContextType } from '../contexts/LanguageContext';

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.containers': 'Containers',
    'nav.gateIn': 'Gate In',
    'nav.gateOut': 'Gate Out',
    'nav.bookingReference': 'Booking Reference',
    'nav.releases': 'Release Orders',
    'nav.edi': 'EDI Management',
    'nav.yard': 'Yard Management',
    'nav.reports': 'Reports',
    'nav.configurations': 'Configurations',
    'nav.depotManagement': 'Depot Management',
    'nav.stackManagement': 'Stack Management',
    'nav.clientPools': 'Client Pools',
    'nav.clientMasterData': 'Client Master Data',
    'nav.userManagement': 'User Management',
    'nav.moduleAccess': 'Module Access',
    'nav.logout': 'Sign Out',

    // Dashboard
    'dashboard.title': 'Container Depot Management',
    'dashboard.welcome': 'Welcome back',
    'dashboard.stats.containers': 'Total Containers',
    'dashboard.stats.in': 'Containers In',
    'dashboard.stats.out': 'Containers Out',
    'dashboard.stats.pending': 'Pending Release Orders',
    'dashboard.stats.movements': 'Today\'s Movements',
    'dashboard.stats.revenue': 'Monthly Revenue',
    'dashboard.stats.occupancy': 'Occupancy Rate',
    'dashboard.stats.damaged': 'Damaged Containers',
    'dashboard.stats.maintenance': 'In Maintenance',
    'dashboard.stats.cleaning': 'In Cleaning',
    'dashboard.multiDepot.global': 'Global Performance',
    'dashboard.multiDepot.current': 'Current Depot',
    'dashboard.multiDepot.allDepots': 'All Depots',
    'dashboard.clientNotice': 'You are viewing data for your company only',

    // Containers
    'containers.title': 'Container Management',
    'containers.gate_in': 'Gate In',
    'containers.gate_out': 'Gate Out',
    'containers.search': 'Search containers...',
    'containers.searchYour': 'Search your containers...',
    'containers.status.inDepot': 'In Depot',
    'containers.status.outDepot': 'Out Depot',
    'containers.status.inService': 'In Service',
    'containers.status.maintenance': 'Maintenance',
    'containers.status.cleaning': 'Cleaning',
    'containers.type.dry': 'Dry Container',
    'containers.type.reefer': 'Reefer Container',
    'containers.type.tank': 'Tank Container',
    'containers.type.flatRack': 'Flat Rack',
    'containers.type.openTop': 'Open Top',
    'containers.size.20ft': '20 Feet',
    'containers.size.40ft': '40 Feet',
    'containers.viewDetails': 'View Details',
    'containers.editContainer': 'Edit Container',
    'containers.auditLog': 'Audit Log',
    'containers.damage.reports': 'Damage Reports',
    'containers.damage.none': 'No damage reports recorded',
    'containers.damage.add': 'Add Damage Report',
    'containers.damage.describe': 'Describe damage...',

    // Gate Operations
    'gate.in.title': 'Gate In Management',
    'gate.in.new': 'New Gate In',
    'gate.in.pending': 'Pending Operations',
    'gate.in.completed': 'Completed Operations',
    'gate.in.stats.today': 'Today\'s Gate Ins',
    'gate.in.stats.pending': 'Pending Operations',
    'gate.in.stats.processed': 'Containers Processed',
    'gate.in.stats.damaged': 'Damaged Containers',
    'gate.in.form.containerInfo': 'Container Information',
    'gate.in.form.transportInfo': 'Transport Information',
    'gate.in.form.timeTracking': 'Time Tracking',
    'gate.in.form.containerNumber': 'Container Number',
    'gate.in.form.containerSize': 'Container Size',
    'gate.in.form.containerType': 'Container Type',
    'gate.in.form.quantity': 'Quantity',
    'gate.in.form.status': 'Container Status',
    'gate.in.form.damage': 'Damage Status',
    'gate.in.form.client': 'Client',
    'gate.in.form.booking': 'Booking Reference',
    'gate.in.form.driver': 'Driver Name',
    'gate.in.form.truck': 'Truck Number',
    'gate.in.form.transport': 'Transport Company',
    'gate.in.form.arrivalDate': 'Arrival Date',
    'gate.in.form.arrivalTime': 'Arrival Time',
    'gate.in.form.notes': 'Additional Notes',
    'gate.in.validation.required': 'This field is required',
    'gate.in.validation.containerFormat': 'Invalid container number format',
    'gate.in.validation.validFormat': 'Valid format',

    'gate.out.title': 'Gate Out Management',
    'gate.out.new': 'New Gate Out',
    'gate.out.pending': 'Pending Operations',
    'gate.out.stats.today': 'Today\'s Gate Outs',
    'gate.out.stats.pending': 'Pending Operations',
    'gate.out.stats.processed': 'Containers Processed',
    'gate.out.stats.issues': 'Issues Reported',
    'gate.out.form.booking': 'Booking Selection',
    'gate.out.form.transport': 'Transport Information',
    'gate.out.form.containers': 'Container Numbers',
    'gate.out.form.selectBooking': 'Select Booking',
    'gate.out.form.driver': 'Driver Name',
    'gate.out.form.vehicle': 'Vehicle Number',
    'gate.out.form.company': 'Transport Company',
    'gate.out.form.vehicleNumberError': 'Truck {truck} has a pending operation in progress. Please complete or cancel the existing operation before proceeding.',
    'gate.out.completion.title': 'Complete Gate Out',
    'gate.out.completion.containers': 'Container Numbers',
    'gate.out.completion.confirm': 'Confirm Container Number',
    'gate.out.completion.gateOutTime': 'Gate Out Date & Time',

    // Release Orders
    'releases.title': 'Release Orders',
    'releases.booking.title': 'Booking Management',
    'releases.create': 'Create Release Order',
    'releases.createBooking': 'Create Booking',
    'releases.pending': 'Pending Validation',
    'releases.validated': 'Validated',
    'releases.executed': 'Executed',
    'releases.completed': 'Completed',
    'releases.cancelled': 'Cancelled',
    'releases.inProcess': 'In Process',
    'releases.stats.total': 'Total Bookings',
    'releases.stats.pending': 'Pending',
    'releases.stats.validated': 'Validated',
    'releases.stats.completed': 'Completed',
    'releases.form.bookingInfo': 'Booking Information',
    'releases.form.clientInfo': 'Client Information',
    'releases.form.quantities': 'Container Quantities',
    'releases.form.bookingNumber': 'Booking Reference Number',
    'releases.form.bookingType': 'Booking Type',
    'releases.form.client': 'Select Client',
    'releases.form.threshold': 'Maximum Quantity Threshold',
    'releases.form.containers20': '20" Containers',
    'releases.form.containers40': '40" Containers',
    'releases.form.notes': 'Notes',
    'releases.breakdown.required': 'Detailed breakdown required',
    'releases.breakdown.summary': 'Container Summary',

    // Yard Management
    'yard.title': 'Yard Management',
    'yard.search': 'Container Search',
    'yard.searchContainer': 'Search & Locate',
    'yard.selectedContainer': 'Selected Container',
    'yard.resetView': 'Reset to Full Yard View',
    'yard.occupancy': 'Occupancy',
    'yard.capacity': 'Capacity',
    'yard.utilization': 'Utilization',
    'yard.sections': 'Sections',
    'yard.stacks': 'Total Stacks',
    'yard.stackCapacity': 'Total Stack Capacity',

    // Depot Management
    'depot.title': 'Depot Management',
    'depot.create': 'Create Depot',
    'depot.edit': 'Edit Depot',
    'depot.view': 'View Details',
    'depot.assign': 'Assign Users',
    'depot.delete': 'Delete Depot',
    'depot.stats.total': 'Total Depots',
    'depot.stats.active': 'Active Depots',
    'depot.stats.capacity': 'Total Capacity',
    'depot.stats.occupancy': 'Total Occupancy',
    'depot.form.basicInfo': 'Basic Information',
    'depot.form.contactInfo': 'Contact Information',
    'depot.form.address': 'Address Information',
    'depot.form.name': 'Depot Name',
    'depot.form.code': 'Depot Code',
    'depot.form.description': 'Description',
    'depot.form.location': 'Location',
    'depot.form.capacity': 'Total Capacity',
    'depot.form.layout': 'Layout Type',
    'depot.form.manager': 'Manager Name',
    'depot.form.phone': 'Phone',
    'depot.form.email': 'Email',
    'depot.form.street': 'Street Address',
    'depot.form.city': 'City',
    'depot.form.state': 'State/Region',
    'depot.form.zipCode': 'ZIP Code',
    'depot.form.country': 'Country',
    'depot.form.timezone': 'Timezone',
    'depot.form.status': 'Status',
    'depot.layout.yirima': 'Yirima Grid',
    'depot.layout.tantarelli': 'Tantarelli Layout',

    // Stack Management
    'stack.title': 'Stack Management',
    'stack.configuration': 'Stack Configuration',
    'stack.rules': 'Configuration Rules',
    'stack.pairing': 'Valid Stack Pairs for 40ft Containers',
    'stack.search': 'Search stacks or sections...',
    'stack.size20': '20ft',
    'stack.size40': '40ft',
    'stack.special': 'Special',
    'stack.regular': 'Regular',
    'stack.assigned': 'Assigned Client',
    'stack.unassigned': 'Unassigned',
    'stack.exclusive': 'Exclusive',
    'stack.shared': 'Shared',
    'stack.saveChanges': 'Save Changes',
    'stack.resetChanges': 'Reset',
    'stack.rules.special': 'Special Stacks (01, 31, 101, 103): Can only be set to 20ft containers.',
    'stack.rules.regular': 'Regular Stacks: Can be set to either 20ft or 40ft containers.',
    'stack.rules.pairing': '40ft Assignment: Only available for regular stacks that have an adjacent regular stack to form valid pairs.',
    'stack.rules.updates': 'Paired Updates: When changing a regular stack to 40ft, its adjacent pair will automatically be updated to match.',

    // Client Pools
    'clientPools.title': 'Client Pool Management',
    'clientPools.create': 'Create Client Pool',
    'clientPools.edit': 'Edit Client Pool',
    'clientPools.stats.total': 'Total Pools',
    'clientPools.stats.active': 'Active Clients',
    'clientPools.stats.stacks': 'Assigned Stacks',
    'clientPools.stats.utilization': 'Avg Utilization',
    'clientPools.form.clientInfo': 'Client Information',
    'clientPools.form.stackAssignment': 'Stack Assignment',
    'clientPools.form.additionalInfo': 'Additional Information',
    'clientPools.form.selectClient': 'Select Client',
    'clientPools.form.contractStart': 'Contract Start Date',
    'clientPools.form.contractEnd': 'Contract End Date',
    'clientPools.form.notes': 'Notes & Special Instructions',
    'clientPools.form.capacity': 'Capacity',
    'clientPools.form.selected': 'Selected',
    'clientPools.form.stacks': 'stacks',
    'clientPools.form.containers': 'containers',
    'clientPools.priority.high': 'High',
    'clientPools.priority.medium': 'Medium',
    'clientPools.priority.low': 'Low',

    // Client Master Data
    'clients.title': 'Client Master Data',
    'clients.add': 'Add Client',
    'clients.edit': 'Edit Client',
    'clients.view': 'View Details',
    'clients.delete': 'Delete Client',
    'clients.stats.total': 'Total Customers',
    'clients.stats.active': 'Active Customers',
    'clients.stats.creditLimit': 'Total Credit Limit',
    'clients.stats.avgPayment': 'Avg Payment Terms',
    'clients.form.basicInfo': 'Basic Information',
    'clients.form.address': 'Company Address',
    'clients.form.contact': 'Contact Person',
    'clients.form.billing': 'Billing Address',
    'clients.form.financial': 'Financial Configuration',
    'clients.form.name': 'Company Name',
    'clients.form.code': 'Client Code',
    'clients.form.email': 'Main Email',
    'clients.form.phone': 'Main Phone',
    'clients.form.taxId': 'Tax ID Number',
    'clients.form.contactName': 'Contact Name',
    'clients.form.contactPosition': 'Position/Title',
    'clients.form.contactEmail': 'Contact Email',
    'clients.form.contactPhone': 'Contact Phone',
    'clients.form.paymentTerms': 'Payment Terms (days)',
    'clients.form.freeDays': 'Free Storage Days',
    'clients.form.dailyRate': 'Daily Rate',
    'clients.form.currency': 'Currency',
    'clients.form.sameAddress': 'Same address as company',
    'clients.form.notes': 'Notes and Special Instructions',
    'clients.form.active': 'Active Client',

    // User Management
    'users.title': 'User Management',
    'users.add': 'Add User',
    'users.edit': 'Edit User',
    'users.view': 'View Details',
    'users.delete': 'Delete User',
    'users.stats.total': 'Total Users',
    'users.stats.active': 'Active Users',
    'users.stats.admins': 'Administrators',
    'users.stats.online': 'Online Today',
    'users.form.basicInfo': 'Basic Information',
    'users.form.role': 'Role & Permissions',
    'users.form.yardAssignments': 'Yard Assignments',
    'users.form.name': 'Full Name',
    'users.form.email': 'Email Address',
    'users.form.phone': 'Phone Number',
    'users.form.department': 'Department',
    'users.form.company': 'Company',
    'users.form.password': 'Password',
    'users.form.userRole': 'User Role',
    'users.form.active': 'Active User',
    'users.role.admin': 'Administrator',
    'users.role.supervisor': 'Supervisor',
    'users.role.operator': 'Operator',
    'users.role.client': 'Client',
    'users.role.adminDesc': 'Full system access across all modules',
    'users.role.supervisorDesc': 'Operations oversight and management',
    'users.role.operatorDesc': 'Daily operations and container handling',
    'users.role.clientDesc': 'View containers and create release orders',

    // Module Access
    'moduleAccess.title': 'Module Access Management',
    'moduleAccess.bulkActions': 'Bulk Actions',
    'moduleAccess.applyRoleBased': 'Apply Role-Based Access',
    'moduleAccess.enableAll': 'Enable All',
    'moduleAccess.disableAll': 'Disable All',
    'moduleAccess.selectAll': 'Select All',
    'moduleAccess.deselectAll': 'Deselect All',
    'moduleAccess.stats.totalUsers': 'Total Users',
    'moduleAccess.stats.modules': 'Available Modules',
    'moduleAccess.stats.admins': 'Admin Users',
    'moduleAccess.stats.selected': 'Selected Users',
    'moduleAccess.category.core': 'Core',
    'moduleAccess.category.operations': 'Operations',
    'moduleAccess.category.management': 'Management',
    'moduleAccess.category.admin': 'Admin',
    'moduleAccess.roleRestricted': 'Role Restricted',
    'moduleAccess.protected': 'Protected',
    'moduleAccess.system': 'System',

    // Reports & Analytics
    'reports.title': 'Reports & Analytics',
    'reports.billing': 'Billing & Free Days',
    'reports.analytics': 'Analytics',
    'reports.operations': 'Operations',
    'reports.export': 'Export Report',
    'reports.dateRange': 'Date Range',
    'reports.startDate': 'Start date',
    'reports.endDate': 'End date',
    'reports.currentDepot': 'Current Depot',
    'reports.allDepots': 'All Depots',
    'reports.globalView': 'Global View',
    'reports.billing.title': 'Container Billing Details',
    'reports.billing.freeDays': 'Free days calculation and billing information',
    'reports.billing.totalRevenue': 'Total Revenue',
    'reports.billing.activeContainers': 'Active Containers',
    'reports.billing.billableDays': 'Billable Days',
    'reports.billing.avgDays': 'Avg Days in Depot',
    'reports.analytics.movements': 'Container Movements',
    'reports.analytics.distribution': 'Client Distribution',
    'reports.analytics.revenue': 'Revenue Trends',
    'reports.analytics.occupancy': 'Yard Occupancy Trends',
    'reports.analytics.types': 'Container Types Distribution',
    'reports.operations.performance': 'Daily Operations Performance',
    'reports.operations.processing': 'Processing Times vs Targets',
    'reports.operations.hourly': 'Hourly Operations Distribution',
    'reports.operations.quality': 'Quality Metrics',
    'reports.operations.equipment': 'Equipment Utilization',

    // EDI Management
    'edi.title': 'EDI Management',
    'edi.configuration': 'Configuration',
    'edi.checkAcknowledgments': 'Check Acknowledgments',
    'edi.processFile': 'Process EDI from File',
    'edi.fileType': 'File Type',
    'edi.operation': 'Operation',
    'edi.selectFile': 'Select File',
    'edi.processSend': 'Process & Send',
    'edi.transmissionHistory': 'Transmission History',
    'edi.stats.sent': 'Total Sent',
    'edi.stats.pending': 'Pending',
    'edi.stats.failed': 'Failed',
    'edi.stats.acknowledged': 'Acknowledged',
    'edi.status.pending': 'Pending',
    'edi.status.sent': 'Sent',
    'edi.status.failed': 'Failed',
    'edi.status.acknowledged': 'Acknowledged',
    'edi.retry': 'Retry',
    'edi.view': 'View',

    // Common
    'common.status': 'Status',
    'common.actions': 'Actions',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.close': 'Close',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.delete': 'Delete',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.loading': 'Loading...',
    'common.processing': 'Processing...',
    'common.saving': 'Saving...',
    'common.updating': 'Updating...',
    'common.creating': 'Creating...',
    'common.deleting': 'Deleting...',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.info': 'Information',
    'common.required': 'Required',
    'common.optional': 'Optional',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.all': 'All',
    'common.none': 'None',
    'common.total': 'Total',
    'common.available': 'Available',
    'common.capacity': 'Capacity',
    'common.utilization': 'Utilization',
    'common.location': 'Location',
    'common.client': 'Client',
    'common.container': 'Container',
    'common.containers': 'Containers',
    'common.type': 'Type',
    'common.size': 'Size',
    'common.quantity': 'Quantity',
    'common.notes': 'Notes',
    'common.description': 'Description',
    'common.name': 'Name',
    'common.code': 'Code',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.city': 'City',
    'common.country': 'Country',
    'common.department': 'Department',
    'common.company': 'Company',
    'common.role': 'Role',
    'common.permission': 'Permission',
    'common.access': 'Access',
    'common.denied': 'Access Denied',
    'common.restricted': 'Access Restricted',
    'common.unauthorized': 'You don\'t have permission to access this module',
    'common.contactAdmin': 'Contact your administrator to request access',
    'common.noData': 'No data found',
    'common.noResults': 'No results found',
    'common.tryAdjusting': 'Try adjusting your search criteria',
    'common.selectDate': 'Select date',
    'common.selectTime': 'Select time',
    'common.currentTime': 'Current time',
    'common.today': 'Today',
    'common.yesterday': 'Yesterday',
    'common.tomorrow': 'Tomorrow',
    'common.thisWeek': 'This week',
    'common.thisMonth': 'This month',
    'common.lastMonth': 'Last month',
    'common.thisYear': 'This year',
    'common.damaged': 'Damaged',
    'common.undamaged': 'Good condition',
    'common.priority': 'Priority',
    'common.urgent': 'Urgent',
    'common.normal': 'Normal',
    'common.low': 'Low'
  },
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.containers': 'Conteneurs',
    'nav.gateIn': 'Entrée Portail',
    'nav.gateOut': 'Sortie Portail',
    'nav.bookingReference': 'Référence de Réservation',
    'nav.releases': 'Ordres de sortie',
    'nav.edi': 'Gestion EDI',
    'nav.yard': 'Gestion de Cour',
    'nav.reports': 'Rapports',
    'nav.configurations': 'Configurations',
    'nav.depotManagement': 'Gestion des Dépôts',
    'nav.stackManagement': 'Gestion des Piles',
    'nav.clientPools': 'Pools Clients',
    'nav.clientMasterData': 'Données Maîtres Clients',
    'nav.userManagement': 'Gestion des Utilisateurs',
    'nav.moduleAccess': 'Accès aux Modules',
    'nav.logout': 'Se déconnecter',

    // Dashboard
    'dashboard.title': 'Gestion de Dépôt de Conteneurs',
    'dashboard.welcome': 'Bon retour',
    'dashboard.stats.containers': 'Total Conteneurs',
    'dashboard.stats.in': 'Conteneurs Entrés',
    'dashboard.stats.out': 'Conteneurs Sortis',
    'dashboard.stats.pending': 'Ordres en Attente',
    'dashboard.stats.movements': 'Mouvements du Jour',
    'dashboard.stats.revenue': 'Revenus Mensuels',
    'dashboard.stats.occupancy': 'Taux d\'Occupation',
    'dashboard.stats.damaged': 'Conteneurs Endommagés',
    'dashboard.stats.maintenance': 'En Maintenance',
    'dashboard.stats.cleaning': 'En Nettoyage',
    'dashboard.multiDepot.global': 'Performance Globale',
    'dashboard.multiDepot.current': 'Dépôt Actuel',
    'dashboard.multiDepot.allDepots': 'Tous les Dépôts',
    'dashboard.clientNotice': 'Vous consultez les données de votre entreprise uniquement',

    // Containers
    'containers.title': 'Gestion des Conteneurs',
    'containers.gate_in': 'Entrée',
    'containers.gate_out': 'Sortie',
    'containers.search': 'Rechercher des conteneurs...',
    'containers.searchYour': 'Rechercher vos conteneurs...',
    'containers.status.inDepot': 'Dans le Dépôt',
    'containers.status.outDepot': 'Hors Dépôt',
    'containers.status.inService': 'En Service',
    'containers.status.maintenance': 'Maintenance',
    'containers.status.cleaning': 'Nettoyage',
    'containers.type.dry': 'Conteneur Sec',
    'containers.type.reefer': 'Conteneur Frigorifique',
    'containers.type.tank': 'Conteneur Citerne',
    'containers.type.flatRack': 'Plate-forme',
    'containers.type.openTop': 'Toit Ouvert',
    'containers.size.20ft': '20 Pieds',
    'containers.size.40ft': '40 Pieds',
    'containers.viewDetails': 'Voir Détails',
    'containers.editContainer': 'Modifier Conteneur',
    'containers.auditLog': 'Journal d\'Audit',
    'containers.damage.reports': 'Rapports de Dommages',
    'containers.damage.none': 'Aucun rapport de dommage enregistré',
    'containers.damage.add': 'Ajouter Rapport de Dommage',
    'containers.damage.describe': 'Décrire les dommages...',

    // Gate Operations
    'gate.in.title': 'Gestion des Entrées',
    'gate.in.new': 'Nouvelle Entrée',
    'gate.in.pending': 'Opérations en Attente',
    'gate.in.completed': 'Opérations Terminées',
    'gate.in.stats.today': 'Entrées d\'Aujourd\'hui',
    'gate.in.stats.pending': 'Opérations en Attente',
    'gate.in.stats.processed': 'Conteneurs Traités',
    'gate.in.stats.damaged': 'Conteneurs Endommagés',
    'gate.in.form.containerInfo': 'Informations du Conteneur',
    'gate.in.form.transportInfo': 'Informations de Transport',
    'gate.in.form.timeTracking': 'Suivi du Temps',
    'gate.in.form.containerNumber': 'Numéro de Conteneur',
    'gate.in.form.containerSize': 'Taille du Conteneur',
    'gate.in.form.containerType': 'Type de Conteneur',
    'gate.in.form.quantity': 'Quantité',
    'gate.in.form.status': 'Statut du Conteneur',
    'gate.in.form.damage': 'Statut des Dommages',
    'gate.in.form.client': 'Client',
    'gate.in.form.booking': 'Référence de Réservation',
    'gate.in.form.driver': 'Nom du Chauffeur',
    'gate.in.form.truck': 'Numéro de Camion',
    'gate.in.form.transport': 'Entreprise de Transport',
    'gate.in.form.arrivalDate': 'Date d\'Arrivée',
    'gate.in.form.arrivalTime': 'Heure d\'Arrivée',
    'gate.in.form.notes': 'Notes Supplémentaires',
    'gate.in.validation.required': 'Ce champ est obligatoire',
    'gate.in.validation.containerFormat': 'Format de numéro de conteneur invalide',
    'gate.in.validation.validFormat': 'Format valide',

    'gate.out.title': 'Gestion des Sorties',
    'gate.out.new': 'Nouvelle Sortie',
    'gate.out.pending': 'Opérations en Attente',
    'gate.out.stats.today': 'Sorties d\'Aujourd\'hui',
    'gate.out.stats.pending': 'Opérations en Attente',
    'gate.out.stats.processed': 'Conteneurs Traités',
    'gate.out.stats.issues': 'Problèmes Signalés',
    'gate.out.form.booking': 'Sélection de Réservation',
    'gate.out.form.transport': 'Informations de Transport',
    'gate.out.form.containers': 'Numéros de Conteneurs',
    'gate.out.form.selectBooking': 'Sélectionner Réservation',
    'gate.out.form.driver': 'Nom du Chauffeur',
    'gate.out.form.vehicle': 'Numéro de Véhicule',
    'gate.out.form.company': 'Entreprise de Transport',
    'gate.out.form.vehicleNumberError': 'Le camion {truck} a une opération en attente en cours. Veuillez terminer ou annuler l\'opération existante avant de continuer.',
    'gate.out.completion.title': 'Terminer la Sortie',
    'gate.out.completion.containers': 'Numéros de Conteneurs',
    'gate.out.completion.confirm': 'Confirmer le Numéro de Conteneur',
    'gate.out.completion.gateOutTime': 'Date et Heure de Sortie',

    // Release Orders
    'releases.title': 'Ordres de Sortie',
    'releases.booking.title': 'Gestion des Réservations',
    'releases.create': 'Créer un Ordre',
    'releases.createBooking': 'Créer une Réservation',
    'releases.pending': 'En Attente de Validation',
    'releases.validated': 'Validés',
    'releases.executed': 'Exécutés',
    'releases.completed': 'Terminés',
    'releases.cancelled': 'Annulés',
    'releases.inProcess': 'En Cours',
    'releases.stats.total': 'Total Réservations',
    'releases.stats.pending': 'En Attente',
    'releases.stats.validated': 'Validées',
    'releases.stats.completed': 'Terminées',
    'releases.form.bookingInfo': 'Informations de Réservation',
    'releases.form.clientInfo': 'Informations Client',
    'releases.form.quantities': 'Quantités de Conteneurs',
    'releases.form.bookingNumber': 'Numéro de Référence de Réservation',
    'releases.form.bookingType': 'Type de Réservation',
    'releases.form.client': 'Sélectionner Client',
    'releases.form.threshold': 'Seuil de Quantité Maximum',
    'releases.form.containers20': 'Conteneurs 20"',
    'releases.form.containers40': 'Conteneurs 40"',
    'releases.form.notes': 'Notes',
    'releases.breakdown.required': 'Répartition détaillée requise',
    'releases.breakdown.summary': 'Résumé des Conteneurs',

    // Yard Management
    'yard.title': 'Gestion de Cour',
    'yard.search': 'Recherche de Conteneurs',
    'yard.searchContainer': 'Rechercher et Localiser',
    'yard.selectedContainer': 'Conteneur Sélectionné',
    'yard.resetView': 'Réinitialiser à la Vue Complète de la Cour',
    'yard.occupancy': 'Occupation',
    'yard.capacity': 'Capacité',
    'yard.utilization': 'Utilisation',
    'yard.sections': 'Sections',
    'yard.stacks': 'Total des Piles',
    'yard.stackCapacity': 'Capacité Totale des Piles',

    // Depot Management
    'depot.title': 'Gestion des Dépôts',
    'depot.create': 'Créer un Dépôt',
    'depot.edit': 'Modifier le Dépôt',
    'depot.view': 'Voir les Détails',
    'depot.assign': 'Assigner des Utilisateurs',
    'depot.delete': 'Supprimer le Dépôt',
    'depot.stats.total': 'Total des Dépôts',
    'depot.stats.active': 'Dépôts Actifs',
    'depot.stats.capacity': 'Capacité Totale',
    'depot.stats.occupancy': 'Occupation Totale',
    'depot.form.basicInfo': 'Informations de Base',
    'depot.form.contactInfo': 'Informations de Contact',
    'depot.form.address': 'Informations d\'Adresse',
    'depot.form.name': 'Nom du Dépôt',
    'depot.form.code': 'Code du Dépôt',
    'depot.form.description': 'Description',
    'depot.form.location': 'Emplacement',
    'depot.form.capacity': 'Capacité Totale',
    'depot.form.layout': 'Type de Disposition',
    'depot.form.manager': 'Nom du Gestionnaire',
    'depot.form.phone': 'Téléphone',
    'depot.form.email': 'Email',
    'depot.form.street': 'Adresse de la Rue',
    'depot.form.city': 'Ville',
    'depot.form.state': 'État/Région',
    'depot.form.zipCode': 'Code Postal',
    'depot.form.country': 'Pays',
    'depot.form.timezone': 'Fuseau Horaire',
    'depot.form.status': 'Statut',
    'depot.layout.yirima': 'Grille Yirima',
    'depot.layout.tantarelli': 'Disposition Tantarelli',

    // Stack Management
    'stack.title': 'Gestion des Piles',
    'stack.configuration': 'Configuration des Piles',
    'stack.rules': 'Règles de Configuration',
    'stack.pairing': 'Paires de Piles Valides pour Conteneurs 40ft',
    'stack.search': 'Rechercher des piles ou sections...',
    'stack.size20': '20ft',
    'stack.size40': '40ft',
    'stack.special': 'Spéciale',
    'stack.regular': 'Régulière',
    'stack.assigned': 'Client Assigné',
    'stack.unassigned': 'Non Assignée',
    'stack.exclusive': 'Exclusif',
    'stack.shared': 'Partagé',
    'stack.saveChanges': 'Sauvegarder les Modifications',
    'stack.resetChanges': 'Réinitialiser',
    'stack.rules.special': 'Piles Spéciales (01, 31, 101, 103) : Ne peuvent être configurées que pour des conteneurs de 20 pieds.',
    'stack.rules.regular': 'Piles Régulières : Peuvent être configurées pour des conteneurs de 20 ou 40 pieds.',
    'stack.rules.pairing': 'Attribution 40 pieds : Disponible uniquement pour les piles régulières qui ont une pile régulière adjacente pour former des paires valides.',
    'stack.rules.updates': 'Mises à jour Appariées : Lors du changement d\'une pile régulière vers 40 pieds, sa paire adjacente sera automatiquement mise à jour pour correspondre.',

    // Client Pools
    'clientPools.title': 'Gestion des Pools Clients',
    'clientPools.create': 'Créer un Pool Client',
    'clientPools.edit': 'Modifier le Pool Client',
    'clientPools.stats.total': 'Total des Pools',
    'clientPools.stats.active': 'Clients Actifs',
    'clientPools.stats.stacks': 'Piles Assignées',
    'clientPools.stats.utilization': 'Utilisation Moyenne',
    'clientPools.form.clientInfo': 'Informations Client',
    'clientPools.form.stackAssignment': 'Attribution des Piles',
    'clientPools.form.additionalInfo': 'Informations Supplémentaires',
    'clientPools.form.selectClient': 'Sélectionner un Client',
    'clientPools.form.contractStart': 'Date de Début de Contrat',
    'clientPools.form.contractEnd': 'Date de Fin de Contrat',
    'clientPools.form.notes': 'Notes et Instructions Spéciales',
    'clientPools.form.capacity': 'Capacité',
    'clientPools.form.selected': 'Sélectionnées',
    'clientPools.form.stacks': 'piles',
    'clientPools.form.containers': 'conteneurs',
    'clientPools.priority.high': 'Élevée',
    'clientPools.priority.medium': 'Moyenne',
    'clientPools.priority.low': 'Faible',

    // Client Master Data
    'clients.title': 'Données Maîtres Clients',
    'clients.add': 'Ajouter un Client',
    'clients.edit': 'Modifier le Client',
    'clients.view': 'Voir les Détails',
    'clients.delete': 'Supprimer le Client',
    'clients.stats.total': 'Total Clients',
    'clients.stats.active': 'Clients Actifs',
    'clients.stats.creditLimit': 'Limite de Crédit Totale',
    'clients.stats.avgPayment': 'Conditions de Paiement Moyennes',
    'clients.form.basicInfo': 'Informations de Base',
    'clients.form.address': 'Adresse de l\'Entreprise',
    'clients.form.contact': 'Personne de Contact',
    'clients.form.billing': 'Adresse de Facturation',
    'clients.form.financial': 'Configuration Financière',
    'clients.form.name': 'Nom de l\'Entreprise',
    'clients.form.code': 'Code Client',
    'clients.form.email': 'Email Principal',
    'clients.form.phone': 'Téléphone Principal',
    'clients.form.taxId': 'Numéro d\'Identification Fiscale',
    'clients.form.contactName': 'Nom du Contact',
    'clients.form.contactPosition': 'Poste/Fonction',
    'clients.form.contactEmail': 'Email de Contact',
    'clients.form.contactPhone': 'Téléphone de Contact',
    'clients.form.paymentTerms': 'Conditions de Paiement (jours)',
    'clients.form.freeDays': 'Jours de Stockage Gratuits',
    'clients.form.dailyRate': 'Tarif Journalier',
    'clients.form.currency': 'Devise',
    'clients.form.sameAddress': 'Même adresse que l\'entreprise',
    'clients.form.notes': 'Notes et Instructions Spéciales',
    'clients.form.active': 'Client Actif',

    // User Management
    'users.title': 'Gestion des Utilisateurs',
    'users.add': 'Ajouter un Utilisateur',
    'users.edit': 'Modifier l\'Utilisateur',
    'users.view': 'Voir les Détails',
    'users.delete': 'Supprimer l\'Utilisateur',
    'users.stats.total': 'Total des Utilisateurs',
    'users.stats.active': 'Utilisateurs Actifs',
    'users.stats.admins': 'Administrateurs',
    'users.stats.online': 'En Ligne Aujourd\'hui',
    'users.form.basicInfo': 'Informations de Base',
    'users.form.role': 'Rôle et Permissions',
    'users.form.yardAssignments': 'Attributions de Cour',
    'users.form.name': 'Nom Complet',
    'users.form.email': 'Adresse Email',
    'users.form.phone': 'Numéro de Téléphone',
    'users.form.department': 'Département',
    'users.form.company': 'Entreprise',
    'users.form.password': 'Mot de Passe',
    'users.form.userRole': 'Rôle Utilisateur',
    'users.form.active': 'Utilisateur Actif',
    'users.role.admin': 'Administrateur',
    'users.role.supervisor': 'Superviseur',
    'users.role.operator': 'Opérateur',
    'users.role.client': 'Client',
    'users.role.adminDesc': 'Accès complet au système sur tous les modules',
    'users.role.supervisorDesc': 'Supervision des opérations et gestion',
    'users.role.operatorDesc': 'Opérations quotidiennes et manipulation des conteneurs',
    'users.role.clientDesc': 'Voir les conteneurs et créer des ordres de libération',

    // Module Access
    'moduleAccess.title': 'Gestion des Accès aux Modules',
    'moduleAccess.bulkActions': 'Actions en Lot',
    'moduleAccess.applyRoleBased': 'Appliquer l\'Accès Basé sur le Rôle',
    'moduleAccess.enableAll': 'Activer Tout',
    'moduleAccess.disableAll': 'Désactiver Tout',
    'moduleAccess.selectAll': 'Sélectionner Tout',
    'moduleAccess.deselectAll': 'Désélectionner Tout',
    'moduleAccess.stats.totalUsers': 'Total des Utilisateurs',
    'moduleAccess.stats.modules': 'Modules Disponibles',
    'moduleAccess.stats.admins': 'Utilisateurs Admin',
    'moduleAccess.stats.selected': 'Utilisateurs Sélectionnés',
    'moduleAccess.category.core': 'Principal',
    'moduleAccess.category.operations': 'Opérations',
    'moduleAccess.category.management': 'Gestion',
    'moduleAccess.category.admin': 'Administration',
    'moduleAccess.roleRestricted': 'Restreint par Rôle',
    'moduleAccess.protected': 'Protégé',
    'moduleAccess.system': 'Système',

    // Reports & Analytics
    'reports.title': 'Rapports et Analyses',
    'reports.billing': 'Facturation et Jours Gratuits',
    'reports.analytics': 'Analyses',
    'reports.operations': 'Opérations',
    'reports.export': 'Exporter le Rapport',
    'reports.dateRange': 'Plage de Dates',
    'reports.startDate': 'Date de début',
    'reports.endDate': 'Date de fin',
    'reports.currentDepot': 'Dépôt Actuel',
    'reports.allDepots': 'Tous les Dépôts',
    'reports.globalView': 'Vue Globale',
    'reports.billing.title': 'Détails de Facturation des Conteneurs',
    'reports.billing.freeDays': 'Calcul des jours gratuits et informations de facturation',
    'reports.billing.totalRevenue': 'Revenus Totaux',
    'reports.billing.activeContainers': 'Conteneurs Actifs',
    'reports.billing.billableDays': 'Jours Facturables',
    'reports.billing.avgDays': 'Jours Moyens dans le Dépôt',
    'reports.analytics.movements': 'Mouvements de Conteneurs',
    'reports.analytics.distribution': 'Distribution des Clients',
    'reports.analytics.revenue': 'Tendances des Revenus',
    'reports.analytics.occupancy': 'Tendances d\'Occupation de la Cour',
    'reports.analytics.types': 'Distribution des Types de Conteneurs',
    'reports.operations.performance': 'Performance des Opérations Quotidiennes',
    'reports.operations.processing': 'Temps de Traitement vs Objectifs',
    'reports.operations.hourly': 'Distribution des Opérations par Heure',
    'reports.operations.quality': 'Métriques de Qualité',
    'reports.operations.equipment': 'Utilisation de l\'Équipement',

    // EDI Management
    'edi.title': 'Gestion EDI',
    'edi.configuration': 'Configuration',
    'edi.checkAcknowledgments': 'Vérifier les Accusés de Réception',
    'edi.processFile': 'Traiter EDI à partir d\'un Fichier',
    'edi.fileType': 'Type de Fichier',
    'edi.operation': 'Opération',
    'edi.selectFile': 'Sélectionner un Fichier',
    'edi.processSend': 'Traiter et Envoyer',
    'edi.transmissionHistory': 'Historique des Transmissions',
    'edi.stats.sent': 'Total Envoyés',
    'edi.stats.pending': 'En Attente',
    'edi.stats.failed': 'Échoués',
    'edi.stats.acknowledged': 'Accusés de Réception',
    'edi.status.pending': 'En Attente',
    'edi.status.sent': 'Envoyé',
    'edi.status.failed': 'Échoué',
    'edi.status.acknowledged': 'Accusé de Réception',
    'edi.retry': 'Réessayer',
    'edi.view': 'Voir',

    // Common
    'common.status': 'Statut',
    'common.actions': 'Actions',
    'common.date': 'Date',
    'common.time': 'Heure',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.confirm': 'Confirmer',
    'common.close': 'Fermer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.delete': 'Supprimer',
    'common.create': 'Créer',
    'common.update': 'Mettre à jour',
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.export': 'Exporter',
    'common.import': 'Importer',
    'common.loading': 'Chargement...',
    'common.processing': 'Traitement...',
    'common.saving': 'Sauvegarde...',
    'common.updating': 'Mise à jour...',
    'common.creating': 'Création...',
    'common.deleting': 'Suppression...',
    'common.success': 'Succès',
    'common.error': 'Erreur',
    'common.warning': 'Avertissement',
    'common.info': 'Information',
    'common.required': 'Obligatoire',
    'common.optional': 'Optionnel',
    'common.active': 'Actif',
    'common.inactive': 'Inactif',
    'common.enabled': 'Activé',
    'common.disabled': 'Désactivé',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.all': 'Tout',
    'common.none': 'Aucun',
    'common.total': 'Total',
    'common.available': 'Disponible',
    'common.capacity': 'Capacité',
    'common.utilization': 'Utilisation',
    'common.location': 'Emplacement',
    'common.client': 'Client',
    'common.container': 'Conteneur',
    'common.containers': 'Conteneurs',
    'common.type': 'Type',
    'common.size': 'Taille',
    'common.quantity': 'Quantité',
    'common.notes': 'Notes',
    'common.description': 'Description',
    'common.name': 'Nom',
    'common.code': 'Code',
    'common.email': 'Email',
    'common.phone': 'Téléphone',
    'common.address': 'Adresse',
    'common.city': 'Ville',
    'common.country': 'Pays',
    'common.department': 'Département',
    'common.company': 'Entreprise',
    'common.role': 'Rôle',
    'common.permission': 'Permission',
    'common.access': 'Accès',
    'common.denied': 'Accès Refusé',
    'common.restricted': 'Accès Restreint',
    'common.unauthorized': 'Vous n\'avez pas la permission d\'accéder à ce module',
    'common.contactAdmin': 'Contactez votre administrateur pour demander l\'accès',
    'common.noData': 'Aucune donnée trouvée',
    'common.noResults': 'Aucun résultat trouvé',
    'common.tryAdjusting': 'Essayez d\'ajuster vos critères de recherche',
    'common.selectDate': 'Sélectionner une date',
    'common.selectTime': 'Sélectionner une heure',
    'common.currentTime': 'Heure actuelle',
    'common.today': 'Aujourd\'hui',
    'common.yesterday': 'Hier',
    'common.tomorrow': 'Demain',
    'common.thisWeek': 'Cette semaine',
    'common.thisMonth': 'Ce mois',
    'common.lastMonth': 'Le mois dernier',
    'common.thisYear': 'Cette année',
    'common.damaged': 'Endommagé',
    'common.undamaged': 'Bon état',
    'common.priority': 'Priorité',
    'common.urgent': 'Urgent',
    'common.normal': 'Normal',
    'common.low': 'Faible'
  }
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const useLanguageProvider = () => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('language');
    return (stored as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return {
    language,
    setLanguage,
    t
  };
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const languageState = useLanguageProvider();
  return <LanguageContext.Provider value={ languageState }> { children } </LanguageContext.Provider>;
};

export { LanguageContext };
